// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package connectivity

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureIPInformation string = "rc(Windows.Networking.Connectivity.IPInformation;{d85145e0-138f-47d7-9b3a-36bb488cef33})"

type IPInformation struct {
	ole.IUnknown
}

func (impl *IPInformation) GetNetworkAdapter() (*NetworkAdapter, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiIPInformation))
	defer itf.Release()
	v := (*iIPInformation)(unsafe.Pointer(itf))
	return v.GetNetworkAdapter()
}

func (impl *IPInformation) GetPrefixLength() (*foundation.IReference, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiIPInformation))
	defer itf.Release()
	v := (*iIPInformation)(unsafe.Pointer(itf))
	return v.GetPrefixLength()
}

const GUIDiIPInformation string = "d85145e0-138f-47d7-9b3a-36bb488cef33"
const SignatureiIPInformation string = "{d85145e0-138f-47d7-9b3a-36bb488cef33}"

type iIPInformation struct {
	ole.IInspectable
}

type iIPInformationVtbl struct {
	ole.IInspectableVtbl

	GetNetworkAdapter uintptr
	GetPrefixLength   uintptr
}

func (v *iIPInformation) VTable() *iIPInformationVtbl {
	return (*iIPInformationVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iIPInformation) GetNetworkAdapter() (*NetworkAdapter, error) {
	var out *NetworkAdapter
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNetworkAdapter,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out NetworkAdapter
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iIPInformation) GetPrefixLength() (*foundation.IReference, error) {
	var out *foundation.IReference
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPrefixLength,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IReference
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
