// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package connectivity

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureNetworkItem string = "rc(Windows.Networking.Connectivity.NetworkItem;{01bc4d39-f5e0-4567-a28c-42080c831b2b})"

type NetworkItem struct {
	ole.IUnknown
}

func (impl *NetworkItem) GetNetworkId() (syscall.GUID, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiNetworkItem))
	defer itf.Release()
	v := (*iNetworkItem)(unsafe.Pointer(itf))
	return v.GetNetworkId()
}

func (impl *NetworkItem) GetNetworkTypes() (NetworkTypes, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiNetworkItem))
	defer itf.Release()
	v := (*iNetworkItem)(unsafe.Pointer(itf))
	return v.GetNetworkTypes()
}

const GUIDiNetworkItem string = "01bc4d39-f5e0-4567-a28c-42080c831b2b"
const SignatureiNetworkItem string = "{01bc4d39-f5e0-4567-a28c-42080c831b2b}"

type iNetworkItem struct {
	ole.IInspectable
}

type iNetworkItemVtbl struct {
	ole.IInspectableVtbl

	GetNetworkId    uintptr
	GetNetworkTypes uintptr
}

func (v *iNetworkItem) VTable() *iNetworkItemVtbl {
	return (*iNetworkItemVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iNetworkItem) GetNetworkId() (syscall.GUID, error) {
	var out syscall.GUID
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNetworkId,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out syscall.GUID
	)

	if hr != 0 {
		return syscall.GUID{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iNetworkItem) GetNetworkTypes() (NetworkTypes, error) {
	var out NetworkTypes
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNetworkTypes,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out NetworkTypes
	)

	if hr != 0 {
		return NetworkTypesNone, ole.NewError(hr)
	}

	return out, nil
}
