// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package connectivity

type NetworkTypes uint32

const SignatureNetworkTypes string = "enum(Windows.Networking.Connectivity.NetworkTypes;u4)"

const (
	NetworkTypesNone           NetworkTypes = 0
	NetworkTypesInternet       NetworkTypes = 1
	NetworkTypesPrivateNetwork NetworkTypes = 2
)
