// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package streams

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const GUIDIRandomAccessStream string = "905a0fe1-bc53-11df-8c49-001e4fc686da"
const SignatureIRandomAccessStream string = "{905a0fe1-bc53-11df-8c49-001e4fc686da}"

type IRandomAccessStream struct {
	ole.IInspectable
}

type IRandomAccessStreamVtbl struct {
	ole.IInspectableVtbl

	GetSize           uintptr
	SetSize           uintptr
	GetInputStreamAt  uintptr
	GetOutputStreamAt uintptr
	GetPosition       uintptr
	Seek              uintptr
	CloneStream       uintptr
	GetCanRead        uintptr
	GetCanWrite       uintptr
}

func (v *IRandomAccessStream) VTable() *IRandomAccessStreamVtbl {
	return (*IRandomAccessStreamVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IRandomAccessStream) GetSize() (uint64, error) {
	var out uint64
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSize,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint64
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (impl *IRandomAccessStream) ReadAsync(buffer *IBuffer, count uint32, options InputStreamOptions) (*foundation.IAsyncOperationWithProgress, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIInputStream))
	defer itf.Release()
	v := (*IInputStream)(unsafe.Pointer(itf))
	return v.ReadAsync(buffer, count, options)
}
