// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package advertisement

type BluetoothLEAdvertisementPublisherStatus int32

const SignatureBluetoothLEAdvertisementPublisherStatus string = "enum(Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementPublisherStatus;i4)"

const (
	BluetoothLEAdvertisementPublisherStatusCreated  BluetoothLEAdvertisementPublisherStatus = 0
	BluetoothLEAdvertisementPublisherStatusWaiting  BluetoothLEAdvertisementPublisherStatus = 1
	BluetoothLEAdvertisementPublisherStatusStarted  BluetoothLEAdvertisementPublisherStatus = 2
	BluetoothLEAdvertisementPublisherStatusStopping BluetoothLEAdvertisementPublisherStatus = 3
	BluetoothLEAdvertisementPublisherStatusStopped  BluetoothLEAdvertisementPublisherStatus = 4
	BluetoothLEAdvertisementPublisherStatusAborted  BluetoothLEAdvertisementPublisherStatus = 5
)
