// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package advertisement

type BluetoothLEScanningMode int32

const SignatureBluetoothLEScanningMode string = "enum(Windows.Devices.Bluetooth.Advertisement.BluetoothLEScanningMode;i4)"

const (
	BluetoothLEScanningModePassive BluetoothLEScanningMode = 0
	BluetoothLEScanningModeActive  BluetoothLEScanningMode = 1
	BluetoothLEScanningModeNone    BluetoothLEScanningMode = 2
)
