// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package certificates

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
	"github.com/saltosystems/winrt-go/windows/storage/streams"
)

const SignatureCertificate string = "rc(Windows.Security.Cryptography.Certificates.Certificate;{333f740c-04d8-43b3-b278-8c5fcc9be5a0})"

type Certificate struct {
	ole.IUnknown
}

func (impl *Certificate) BuildChainAsync(certificates *collections.IIterable) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.BuildChainAsync(certificates)
}

func (impl *Certificate) BuildChainWithParametersAsync(certificates *collections.IIterable, parameters *ChainBuildingParameters) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.BuildChainWithParametersAsync(certificates, parameters)
}

func (impl *Certificate) GetSerialNumber() (uint32, []uint8, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetSerialNumber()
}

func (impl *Certificate) GetHashValue() (uint32, []uint8, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetHashValue()
}

func (impl *Certificate) GetHashValueWithAlgorithm(hashAlgorithmName string) (uint32, []uint8, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetHashValueWithAlgorithm(hashAlgorithmName)
}

func (impl *Certificate) GetCertificateBlob() (*streams.IBuffer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetCertificateBlob()
}

func (impl *Certificate) GetSubject() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetSubject()
}

func (impl *Certificate) GetIssuer() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetIssuer()
}

func (impl *Certificate) GetHasPrivateKey() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetHasPrivateKey()
}

func (impl *Certificate) GetIsStronglyProtected() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetIsStronglyProtected()
}

func (impl *Certificate) GetValidFrom() (foundation.DateTime, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetValidFrom()
}

func (impl *Certificate) GetValidTo() (foundation.DateTime, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetValidTo()
}

func (impl *Certificate) GetEnhancedKeyUsages() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetEnhancedKeyUsages()
}

func (impl *Certificate) SetFriendlyName(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.SetFriendlyName(value)
}

func (impl *Certificate) GetFriendlyName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate))
	defer itf.Release()
	v := (*iCertificate)(unsafe.Pointer(itf))
	return v.GetFriendlyName()
}

func (impl *Certificate) GetIsSecurityDeviceBound() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate2))
	defer itf.Release()
	v := (*iCertificate2)(unsafe.Pointer(itf))
	return v.GetIsSecurityDeviceBound()
}

func (impl *Certificate) GetKeyUsages() (*CertificateKeyUsages, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate2))
	defer itf.Release()
	v := (*iCertificate2)(unsafe.Pointer(itf))
	return v.GetKeyUsages()
}

func (impl *Certificate) GetKeyAlgorithmName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate2))
	defer itf.Release()
	v := (*iCertificate2)(unsafe.Pointer(itf))
	return v.GetKeyAlgorithmName()
}

func (impl *Certificate) GetSignatureAlgorithmName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate2))
	defer itf.Release()
	v := (*iCertificate2)(unsafe.Pointer(itf))
	return v.GetSignatureAlgorithmName()
}

func (impl *Certificate) GetSignatureHashAlgorithmName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate2))
	defer itf.Release()
	v := (*iCertificate2)(unsafe.Pointer(itf))
	return v.GetSignatureHashAlgorithmName()
}

func (impl *Certificate) GetSubjectAlternativeName() (*SubjectAlternativeNameInfo, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate2))
	defer itf.Release()
	v := (*iCertificate2)(unsafe.Pointer(itf))
	return v.GetSubjectAlternativeName()
}

func (impl *Certificate) GetIsPerUser() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate3))
	defer itf.Release()
	v := (*iCertificate3)(unsafe.Pointer(itf))
	return v.GetIsPerUser()
}

func (impl *Certificate) GetStoreName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate3))
	defer itf.Release()
	v := (*iCertificate3)(unsafe.Pointer(itf))
	return v.GetStoreName()
}

func (impl *Certificate) GetKeyStorageProviderName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificate3))
	defer itf.Release()
	v := (*iCertificate3)(unsafe.Pointer(itf))
	return v.GetKeyStorageProviderName()
}

const GUIDiCertificate string = "333f740c-04d8-43b3-b278-8c5fcc9be5a0"
const SignatureiCertificate string = "{333f740c-04d8-43b3-b278-8c5fcc9be5a0}"

type iCertificate struct {
	ole.IInspectable
}

type iCertificateVtbl struct {
	ole.IInspectableVtbl

	BuildChainAsync               uintptr
	BuildChainWithParametersAsync uintptr
	GetSerialNumber               uintptr
	GetHashValue                  uintptr
	GetHashValueWithAlgorithm     uintptr
	GetCertificateBlob            uintptr
	GetSubject                    uintptr
	GetIssuer                     uintptr
	GetHasPrivateKey              uintptr
	GetIsStronglyProtected        uintptr
	GetValidFrom                  uintptr
	GetValidTo                    uintptr
	GetEnhancedKeyUsages          uintptr
	SetFriendlyName               uintptr
	GetFriendlyName               uintptr
}

func (v *iCertificate) VTable() *iCertificateVtbl {
	return (*iCertificateVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iCertificate) BuildChainAsync(certificates *collections.IIterable) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().BuildChainAsync,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(certificates)), // in collections.IIterable
		uintptr(unsafe.Pointer(&out)),         // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) BuildChainWithParametersAsync(certificates *collections.IIterable, parameters *ChainBuildingParameters) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().BuildChainWithParametersAsync,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(certificates)), // in collections.IIterable
		uintptr(unsafe.Pointer(parameters)),   // in ChainBuildingParameters
		uintptr(unsafe.Pointer(&out)),         // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) GetSerialNumber() (uint32, []uint8, error) {
	var outSize uint32
	var out []uint8 = make([]uint8, outSize)
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSerialNumber,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outSize)), // out uint32
		uintptr(unsafe.Pointer(&out[0])),  // out uint8
	)

	if hr != 0 {
		return 0, nil, ole.NewError(hr)
	}

	return outSize, out, nil
}

func (v *iCertificate) GetHashValue() (uint32, []uint8, error) {
	var outSize uint32
	var out []uint8 = make([]uint8, outSize)
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetHashValue,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outSize)), // out uint32
		uintptr(unsafe.Pointer(&out[0])),  // out uint8
	)

	if hr != 0 {
		return 0, nil, ole.NewError(hr)
	}

	return outSize, out, nil
}

func (v *iCertificate) GetHashValueWithAlgorithm(hashAlgorithmName string) (uint32, []uint8, error) {
	var outSize uint32
	var out []uint8 = make([]uint8, outSize)
	hashAlgorithmNameHStr, err := ole.NewHString(hashAlgorithmName)
	if err != nil {
		return 0, nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetHashValueWithAlgorithm,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(hashAlgorithmNameHStr),    // in string
		uintptr(unsafe.Pointer(&outSize)), // out uint32
		uintptr(unsafe.Pointer(&out[0])),  // out uint8
	)

	if hr != 0 {
		return 0, nil, ole.NewError(hr)
	}

	return outSize, out, nil
}

func (v *iCertificate) GetCertificateBlob() (*streams.IBuffer, error) {
	var out *streams.IBuffer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCertificateBlob,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out streams.IBuffer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) GetSubject() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSubject,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iCertificate) GetIssuer() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIssuer,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iCertificate) GetHasPrivateKey() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetHasPrivateKey,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) GetIsStronglyProtected() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsStronglyProtected,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) GetValidFrom() (foundation.DateTime, error) {
	var out foundation.DateTime
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetValidFrom,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.DateTime
	)

	if hr != 0 {
		return foundation.DateTime{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) GetValidTo() (foundation.DateTime, error) {
	var out foundation.DateTime
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetValidTo,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.DateTime
	)

	if hr != 0 {
		return foundation.DateTime{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) GetEnhancedKeyUsages() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetEnhancedKeyUsages,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate) SetFriendlyName(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetFriendlyName,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificate) GetFriendlyName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetFriendlyName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

const GUIDiCertificate2 string = "17b8374c-8a25-4d96-a492-8fc29ac4fda6"
const SignatureiCertificate2 string = "{17b8374c-8a25-4d96-a492-8fc29ac4fda6}"

type iCertificate2 struct {
	ole.IInspectable
}

type iCertificate2Vtbl struct {
	ole.IInspectableVtbl

	GetIsSecurityDeviceBound      uintptr
	GetKeyUsages                  uintptr
	GetKeyAlgorithmName           uintptr
	GetSignatureAlgorithmName     uintptr
	GetSignatureHashAlgorithmName uintptr
	GetSubjectAlternativeName     uintptr
}

func (v *iCertificate2) VTable() *iCertificate2Vtbl {
	return (*iCertificate2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iCertificate2) GetIsSecurityDeviceBound() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsSecurityDeviceBound,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate2) GetKeyUsages() (*CertificateKeyUsages, error) {
	var out *CertificateKeyUsages
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeyUsages,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out CertificateKeyUsages
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate2) GetKeyAlgorithmName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeyAlgorithmName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iCertificate2) GetSignatureAlgorithmName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSignatureAlgorithmName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iCertificate2) GetSignatureHashAlgorithmName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSignatureHashAlgorithmName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iCertificate2) GetSubjectAlternativeName() (*SubjectAlternativeNameInfo, error) {
	var out *SubjectAlternativeNameInfo
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSubjectAlternativeName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out SubjectAlternativeNameInfo
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiCertificate3 string = "be51a966-ae5f-4652-ace7-c6d7e7724cf3"
const SignatureiCertificate3 string = "{be51a966-ae5f-4652-ace7-c6d7e7724cf3}"

type iCertificate3 struct {
	ole.IInspectable
}

type iCertificate3Vtbl struct {
	ole.IInspectableVtbl

	GetIsPerUser              uintptr
	GetStoreName              uintptr
	GetKeyStorageProviderName uintptr
}

func (v *iCertificate3) VTable() *iCertificate3Vtbl {
	return (*iCertificate3Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iCertificate3) GetIsPerUser() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsPerUser,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificate3) GetStoreName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStoreName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iCertificate3) GetKeyStorageProviderName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeyStorageProviderName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

const GUIDiCertificateFactory string = "17b4221c-4baf-44a2-9608-04fb62b16942"
const SignatureiCertificateFactory string = "{17b4221c-4baf-44a2-9608-04fb62b16942}"

type iCertificateFactory struct {
	ole.IInspectable
}

type iCertificateFactoryVtbl struct {
	ole.IInspectableVtbl

	CertificateCreateCertificate uintptr
}

func (v *iCertificateFactory) VTable() *iCertificateFactoryVtbl {
	return (*iCertificateFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func CertificateCreateCertificate(certBlob *streams.IBuffer) (*Certificate, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Cryptography.Certificates.Certificate", ole.NewGUID(GUIDiCertificateFactory))
	if err != nil {
		return nil, err
	}
	v := (*iCertificateFactory)(unsafe.Pointer(inspectable))

	var out *Certificate
	hr, _, _ := syscall.SyscallN(
		v.VTable().CertificateCreateCertificate,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(certBlob)), // in streams.IBuffer
		uintptr(unsafe.Pointer(&out)),     // out Certificate
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
