// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package certificates

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureCertificateKeyUsages string = "rc(Windows.Security.Cryptography.Certificates.CertificateKeyUsages;{6ac6206f-e1cf-486a-b485-a69c83e46fd1})"

type CertificateKeyUsages struct {
	ole.IUnknown
}

func NewCertificateKeyUsages() (*CertificateKeyUsages, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Security.Cryptography.Certificates.CertificateKeyUsages")
	if err != nil {
		return nil, err
	}
	return (*CertificateKeyUsages)(unsafe.Pointer(inspectable)), nil
}

func (impl *CertificateKeyUsages) GetEncipherOnly() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetEncipherOnly()
}

func (impl *CertificateKeyUsages) SetEncipherOnly(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetEncipherOnly(value)
}

func (impl *CertificateKeyUsages) GetCrlSign() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetCrlSign()
}

func (impl *CertificateKeyUsages) SetCrlSign(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetCrlSign(value)
}

func (impl *CertificateKeyUsages) GetKeyCertificateSign() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetKeyCertificateSign()
}

func (impl *CertificateKeyUsages) SetKeyCertificateSign(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetKeyCertificateSign(value)
}

func (impl *CertificateKeyUsages) GetKeyAgreement() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetKeyAgreement()
}

func (impl *CertificateKeyUsages) SetKeyAgreement(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetKeyAgreement(value)
}

func (impl *CertificateKeyUsages) GetDataEncipherment() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetDataEncipherment()
}

func (impl *CertificateKeyUsages) SetDataEncipherment(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetDataEncipherment(value)
}

func (impl *CertificateKeyUsages) GetKeyEncipherment() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetKeyEncipherment()
}

func (impl *CertificateKeyUsages) SetKeyEncipherment(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetKeyEncipherment(value)
}

func (impl *CertificateKeyUsages) GetNonRepudiation() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetNonRepudiation()
}

func (impl *CertificateKeyUsages) SetNonRepudiation(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetNonRepudiation(value)
}

func (impl *CertificateKeyUsages) GetDigitalSignature() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.GetDigitalSignature()
}

func (impl *CertificateKeyUsages) SetDigitalSignature(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateKeyUsages))
	defer itf.Release()
	v := (*iCertificateKeyUsages)(unsafe.Pointer(itf))
	return v.SetDigitalSignature(value)
}

const GUIDiCertificateKeyUsages string = "6ac6206f-e1cf-486a-b485-a69c83e46fd1"
const SignatureiCertificateKeyUsages string = "{6ac6206f-e1cf-486a-b485-a69c83e46fd1}"

type iCertificateKeyUsages struct {
	ole.IInspectable
}

type iCertificateKeyUsagesVtbl struct {
	ole.IInspectableVtbl

	GetEncipherOnly       uintptr
	SetEncipherOnly       uintptr
	GetCrlSign            uintptr
	SetCrlSign            uintptr
	GetKeyCertificateSign uintptr
	SetKeyCertificateSign uintptr
	GetKeyAgreement       uintptr
	SetKeyAgreement       uintptr
	GetDataEncipherment   uintptr
	SetDataEncipherment   uintptr
	GetKeyEncipherment    uintptr
	SetKeyEncipherment    uintptr
	GetNonRepudiation     uintptr
	SetNonRepudiation     uintptr
	GetDigitalSignature   uintptr
	SetDigitalSignature   uintptr
}

func (v *iCertificateKeyUsages) VTable() *iCertificateKeyUsagesVtbl {
	return (*iCertificateKeyUsagesVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iCertificateKeyUsages) GetEncipherOnly() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetEncipherOnly,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetEncipherOnly(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetEncipherOnly,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateKeyUsages) GetCrlSign() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCrlSign,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetCrlSign(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetCrlSign,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateKeyUsages) GetKeyCertificateSign() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeyCertificateSign,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetKeyCertificateSign(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetKeyCertificateSign,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateKeyUsages) GetKeyAgreement() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeyAgreement,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetKeyAgreement(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetKeyAgreement,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateKeyUsages) GetDataEncipherment() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDataEncipherment,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetDataEncipherment(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetDataEncipherment,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateKeyUsages) GetKeyEncipherment() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeyEncipherment,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetKeyEncipherment(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetKeyEncipherment,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateKeyUsages) GetNonRepudiation() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNonRepudiation,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetNonRepudiation(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetNonRepudiation,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateKeyUsages) GetDigitalSignature() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDigitalSignature,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateKeyUsages) SetDigitalSignature(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetDigitalSignature,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
