// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package certificates

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureCertificateExtension string = "rc(Windows.Security.Cryptography.Certificates.CertificateExtension;{84cf0656-a9e6-454d-8e45-2ea7c4bcd53b})"

type CertificateExtension struct {
	ole.IUnknown
}

func NewCertificateExtension() (*CertificateExtension, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Security.Cryptography.Certificates.CertificateExtension")
	if err != nil {
		return nil, err
	}
	return (*CertificateExtension)(unsafe.Pointer(inspectable)), nil
}

func (impl *CertificateExtension) GetObjectId() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateExtension))
	defer itf.Release()
	v := (*iCertificateExtension)(unsafe.Pointer(itf))
	return v.GetObjectId()
}

func (impl *CertificateExtension) SetObjectId(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateExtension))
	defer itf.Release()
	v := (*iCertificateExtension)(unsafe.Pointer(itf))
	return v.SetObjectId(value)
}

func (impl *CertificateExtension) GetIsCritical() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateExtension))
	defer itf.Release()
	v := (*iCertificateExtension)(unsafe.Pointer(itf))
	return v.GetIsCritical()
}

func (impl *CertificateExtension) SetIsCritical(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateExtension))
	defer itf.Release()
	v := (*iCertificateExtension)(unsafe.Pointer(itf))
	return v.SetIsCritical(value)
}

func (impl *CertificateExtension) EncodeValue(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateExtension))
	defer itf.Release()
	v := (*iCertificateExtension)(unsafe.Pointer(itf))
	return v.EncodeValue(value)
}

func (impl *CertificateExtension) GetValue() (uint32, []uint8, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateExtension))
	defer itf.Release()
	v := (*iCertificateExtension)(unsafe.Pointer(itf))
	return v.GetValue()
}

func (impl *CertificateExtension) SetValue(valueSize uint32, value []uint8) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiCertificateExtension))
	defer itf.Release()
	v := (*iCertificateExtension)(unsafe.Pointer(itf))
	return v.SetValue(valueSize, value)
}

const GUIDiCertificateExtension string = "84cf0656-a9e6-454d-8e45-2ea7c4bcd53b"
const SignatureiCertificateExtension string = "{84cf0656-a9e6-454d-8e45-2ea7c4bcd53b}"

type iCertificateExtension struct {
	ole.IInspectable
}

type iCertificateExtensionVtbl struct {
	ole.IInspectableVtbl

	GetObjectId   uintptr
	SetObjectId   uintptr
	GetIsCritical uintptr
	SetIsCritical uintptr
	EncodeValue   uintptr
	GetValue      uintptr
	SetValue      uintptr
}

func (v *iCertificateExtension) VTable() *iCertificateExtensionVtbl {
	return (*iCertificateExtensionVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iCertificateExtension) GetObjectId() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetObjectId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iCertificateExtension) SetObjectId(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetObjectId,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateExtension) GetIsCritical() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsCritical,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iCertificateExtension) SetIsCritical(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetIsCritical,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateExtension) EncodeValue(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().EncodeValue,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iCertificateExtension) GetValue() (uint32, []uint8, error) {
	var outSize uint32
	var out []uint8 = make([]uint8, outSize)
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetValue,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outSize)), // out uint32
		uintptr(unsafe.Pointer(&out[0])),  // out uint8
	)

	if hr != 0 {
		return 0, nil, ole.NewError(hr)
	}

	return outSize, out, nil
}

func (v *iCertificateExtension) SetValue(valueSize uint32, value []uint8) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetValue,
		uintptr(unsafe.Pointer(v)),         // this
		uintptr(valueSize),                 // in uint32
		uintptr(unsafe.Pointer(&value[0])), // in uint8
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
