// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package certificates

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
)

const SignatureSubjectAlternativeNameInfo string = "rc(Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo;{582859f1-569d-4c20-be7b-4e1c9a0bc52b})"

type SubjectAlternativeNameInfo struct {
	ole.IUnknown
}

func NewSubjectAlternativeNameInfo() (*SubjectAlternativeNameInfo, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo")
	if err != nil {
		return nil, err
	}
	return (*SubjectAlternativeNameInfo)(unsafe.Pointer(inspectable)), nil
}

func (impl *SubjectAlternativeNameInfo) GetEmailName() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo)(unsafe.Pointer(itf))
	return v.GetEmailName()
}

func (impl *SubjectAlternativeNameInfo) GetIPAddress() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo)(unsafe.Pointer(itf))
	return v.GetIPAddress()
}

func (impl *SubjectAlternativeNameInfo) GetUrl() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo)(unsafe.Pointer(itf))
	return v.GetUrl()
}

func (impl *SubjectAlternativeNameInfo) GetDnsName() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo)(unsafe.Pointer(itf))
	return v.GetDnsName()
}

func (impl *SubjectAlternativeNameInfo) GetDistinguishedName() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo)(unsafe.Pointer(itf))
	return v.GetDistinguishedName()
}

func (impl *SubjectAlternativeNameInfo) GetPrincipalName() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo)(unsafe.Pointer(itf))
	return v.GetPrincipalName()
}

func (impl *SubjectAlternativeNameInfo) GetEmailNames() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo2))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo2)(unsafe.Pointer(itf))
	return v.GetEmailNames()
}

func (impl *SubjectAlternativeNameInfo) GetIPAddresses() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo2))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo2)(unsafe.Pointer(itf))
	return v.GetIPAddresses()
}

func (impl *SubjectAlternativeNameInfo) GetUrls() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo2))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo2)(unsafe.Pointer(itf))
	return v.GetUrls()
}

func (impl *SubjectAlternativeNameInfo) GetDnsNames() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo2))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo2)(unsafe.Pointer(itf))
	return v.GetDnsNames()
}

func (impl *SubjectAlternativeNameInfo) GetDistinguishedNames() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo2))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo2)(unsafe.Pointer(itf))
	return v.GetDistinguishedNames()
}

func (impl *SubjectAlternativeNameInfo) GetPrincipalNames() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo2))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo2)(unsafe.Pointer(itf))
	return v.GetPrincipalNames()
}

func (impl *SubjectAlternativeNameInfo) GetExtension() (*CertificateExtension, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSubjectAlternativeNameInfo2))
	defer itf.Release()
	v := (*iSubjectAlternativeNameInfo2)(unsafe.Pointer(itf))
	return v.GetExtension()
}

const GUIDiSubjectAlternativeNameInfo string = "582859f1-569d-4c20-be7b-4e1c9a0bc52b"
const SignatureiSubjectAlternativeNameInfo string = "{582859f1-569d-4c20-be7b-4e1c9a0bc52b}"

type iSubjectAlternativeNameInfo struct {
	ole.IInspectable
}

type iSubjectAlternativeNameInfoVtbl struct {
	ole.IInspectableVtbl

	GetEmailName         uintptr
	GetIPAddress         uintptr
	GetUrl               uintptr
	GetDnsName           uintptr
	GetDistinguishedName uintptr
	GetPrincipalName     uintptr
}

func (v *iSubjectAlternativeNameInfo) VTable() *iSubjectAlternativeNameInfoVtbl {
	return (*iSubjectAlternativeNameInfoVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iSubjectAlternativeNameInfo) GetEmailName() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetEmailName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo) GetIPAddress() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIPAddress,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo) GetUrl() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUrl,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo) GetDnsName() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDnsName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo) GetDistinguishedName() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDistinguishedName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo) GetPrincipalName() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPrincipalName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiSubjectAlternativeNameInfo2 string = "437a78c6-1c51-41ea-b34a-3d654398a370"
const SignatureiSubjectAlternativeNameInfo2 string = "{437a78c6-1c51-41ea-b34a-3d654398a370}"

type iSubjectAlternativeNameInfo2 struct {
	ole.IInspectable
}

type iSubjectAlternativeNameInfo2Vtbl struct {
	ole.IInspectableVtbl

	GetEmailNames         uintptr
	GetIPAddresses        uintptr
	GetUrls               uintptr
	GetDnsNames           uintptr
	GetDistinguishedNames uintptr
	GetPrincipalNames     uintptr
	GetExtension          uintptr
}

func (v *iSubjectAlternativeNameInfo2) VTable() *iSubjectAlternativeNameInfo2Vtbl {
	return (*iSubjectAlternativeNameInfo2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iSubjectAlternativeNameInfo2) GetEmailNames() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetEmailNames,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo2) GetIPAddresses() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIPAddresses,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo2) GetUrls() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUrls,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo2) GetDnsNames() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDnsNames,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo2) GetDistinguishedNames() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDistinguishedNames,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo2) GetPrincipalNames() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPrincipalNames,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iSubjectAlternativeNameInfo2) GetExtension() (*CertificateExtension, error) {
	var out *CertificateExtension
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetExtension,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out CertificateExtension
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
