// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint
package bluetooth

type BluetoothCacheMode int32

const SignatureBluetoothCacheMode string = "enum(Windows.Devices.Bluetooth.BluetoothCacheMode;i4)"

const (
	BluetoothCacheModeCached   BluetoothCacheMode = 0
	BluetoothCacheModeUncached BluetoothCacheMode = 1
)
