// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureBluetoothLEConnectionPhyInfo string = "rc(Windows.Devices.Bluetooth.BluetoothLEConnectionPhyInfo;{9a100bdd-602e-5c27-a1ae-b230015a6394})"

type BluetoothLEConnectionPhyInfo struct {
	ole.IUnknown
}

func (impl *BluetoothLEConnectionPhyInfo) GetIsUncoded1MPhy() (bool, error) {
	itf, err := impl.QueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionPhyInfo))
	if err != nil {
		return false, err
	}
	defer itf.Release()
	v := (*iBluetoothLEConnectionPhyInfo)(unsafe.Pointer(itf))
	return v.GetIsUncoded1MPhy()
}

func (impl *BluetoothLEConnectionPhyInfo) GetIsUncoded2MPhy() (bool, error) {
	itf, err := impl.QueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionPhyInfo))
	if err != nil {
		return false, err
	}
	defer itf.Release()
	v := (*iBluetoothLEConnectionPhyInfo)(unsafe.Pointer(itf))
	return v.GetIsUncoded2MPhy()
}

func (impl *BluetoothLEConnectionPhyInfo) GetIsCodedPhy() (bool, error) {
	itf, err := impl.QueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionPhyInfo))
	if err != nil {
		return false, err
	}
	defer itf.Release()
	v := (*iBluetoothLEConnectionPhyInfo)(unsafe.Pointer(itf))
	return v.GetIsCodedPhy()
}

const GUIDiBluetoothLEConnectionPhyInfo string = "9a100bdd-602e-5c27-a1ae-b230015a6394"
const SignatureiBluetoothLEConnectionPhyInfo string = "{9a100bdd-602e-5c27-a1ae-b230015a6394}"

type iBluetoothLEConnectionPhyInfo struct {
	ole.IInspectable
}

type iBluetoothLEConnectionPhyInfoVtbl struct {
	ole.IInspectableVtbl

	GetIsUncoded1MPhy uintptr
	GetIsUncoded2MPhy uintptr
	GetIsCodedPhy     uintptr
}

func (v *iBluetoothLEConnectionPhyInfo) VTable() *iBluetoothLEConnectionPhyInfoVtbl {
	return (*iBluetoothLEConnectionPhyInfoVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBluetoothLEConnectionPhyInfo) GetIsUncoded1MPhy() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsUncoded1MPhy,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEConnectionPhyInfo) GetIsUncoded2MPhy() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsUncoded2MPhy,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEConnectionPhyInfo) GetIsCodedPhy() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIsCodedPhy,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}
