// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

type BluetoothLEPreferredConnectionParametersRequestStatus int32

const SignatureBluetoothLEPreferredConnectionParametersRequestStatus string = "enum(Windows.Devices.Bluetooth.BluetoothLEPreferredConnectionParametersRequestStatus;i4)"

const (
	BluetoothLEPreferredConnectionParametersRequestStatusUnspecified        BluetoothLEPreferredConnectionParametersRequestStatus = 0
	BluetoothLEPreferredConnectionParametersRequestStatusSuccess            BluetoothLEPreferredConnectionParametersRequestStatus = 1
	BluetoothLEPreferredConnectionParametersRequestStatusDeviceNotAvailable BluetoothLEPreferredConnectionParametersRequestStatus = 2
	BluetoothLEPreferredConnectionParametersRequestStatusAccessDenied       BluetoothLEPreferredConnectionParametersRequestStatus = 3
)
