// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureBluetoothLEPreferredConnectionParameters string = "rc(Windows.Devices.Bluetooth.BluetoothLEPreferredConnectionParameters;{f2f44344-7372-5f7b-9b34-29c944f5a715})"

type BluetoothLEPreferredConnectionParameters struct {
	ole.IUnknown
}

func (impl *BluetoothLEPreferredConnectionParameters) GetLinkTimeout() (uint16, error) {
	itf, err := impl.QueryInterface(ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParameters))
	if err != nil {
		return 0, err
	}
	defer itf.Release()
	v := (*iBluetoothLEPreferredConnectionParameters)(unsafe.Pointer(itf))
	return v.GetLinkTimeout()
}

func (impl *BluetoothLEPreferredConnectionParameters) GetConnectionLatency() (uint16, error) {
	itf, err := impl.QueryInterface(ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParameters))
	if err != nil {
		return 0, err
	}
	defer itf.Release()
	v := (*iBluetoothLEPreferredConnectionParameters)(unsafe.Pointer(itf))
	return v.GetConnectionLatency()
}

func (impl *BluetoothLEPreferredConnectionParameters) GetMinConnectionInterval() (uint16, error) {
	itf, err := impl.QueryInterface(ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParameters))
	if err != nil {
		return 0, err
	}
	defer itf.Release()
	v := (*iBluetoothLEPreferredConnectionParameters)(unsafe.Pointer(itf))
	return v.GetMinConnectionInterval()
}

func (impl *BluetoothLEPreferredConnectionParameters) GetMaxConnectionInterval() (uint16, error) {
	itf, err := impl.QueryInterface(ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParameters))
	if err != nil {
		return 0, err
	}
	defer itf.Release()
	v := (*iBluetoothLEPreferredConnectionParameters)(unsafe.Pointer(itf))
	return v.GetMaxConnectionInterval()
}

const GUIDiBluetoothLEPreferredConnectionParameters string = "f2f44344-7372-5f7b-9b34-29c944f5a715"
const SignatureiBluetoothLEPreferredConnectionParameters string = "{f2f44344-7372-5f7b-9b34-29c944f5a715}"

type iBluetoothLEPreferredConnectionParameters struct {
	ole.IInspectable
}

type iBluetoothLEPreferredConnectionParametersVtbl struct {
	ole.IInspectableVtbl

	GetLinkTimeout           uintptr
	GetConnectionLatency     uintptr
	GetMinConnectionInterval uintptr
	GetMaxConnectionInterval uintptr
}

func (v *iBluetoothLEPreferredConnectionParameters) VTable() *iBluetoothLEPreferredConnectionParametersVtbl {
	return (*iBluetoothLEPreferredConnectionParametersVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBluetoothLEPreferredConnectionParameters) GetLinkTimeout() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLinkTimeout,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEPreferredConnectionParameters) GetConnectionLatency() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetConnectionLatency,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEPreferredConnectionParameters) GetMinConnectionInterval() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMinConnectionInterval,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEPreferredConnectionParameters) GetMaxConnectionInterval() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMaxConnectionInterval,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiBluetoothLEPreferredConnectionParametersStatics string = "0e3e8edc-2751-55aa-a838-8faeee818d72"
const SignatureiBluetoothLEPreferredConnectionParametersStatics string = "{0e3e8edc-2751-55aa-a838-8faeee818d72}"

type iBluetoothLEPreferredConnectionParametersStatics struct {
	ole.IInspectable
}

type iBluetoothLEPreferredConnectionParametersStaticsVtbl struct {
	ole.IInspectableVtbl

	BluetoothLEPreferredConnectionParametersGetBalanced            uintptr
	BluetoothLEPreferredConnectionParametersGetThroughputOptimized uintptr
	BluetoothLEPreferredConnectionParametersGetPowerOptimized      uintptr
}

func (v *iBluetoothLEPreferredConnectionParametersStatics) VTable() *iBluetoothLEPreferredConnectionParametersStaticsVtbl {
	return (*iBluetoothLEPreferredConnectionParametersStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func BluetoothLEPreferredConnectionParametersGetBalanced() (*BluetoothLEPreferredConnectionParameters, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Bluetooth.BluetoothLEPreferredConnectionParameters", ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParametersStatics))
	if err != nil {
		return nil, err
	}
	v := (*iBluetoothLEPreferredConnectionParametersStatics)(unsafe.Pointer(inspectable))

	var out *BluetoothLEPreferredConnectionParameters
	hr, _, _ := syscall.SyscallN(
		v.VTable().BluetoothLEPreferredConnectionParametersGetBalanced,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out BluetoothLEPreferredConnectionParameters
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func BluetoothLEPreferredConnectionParametersGetThroughputOptimized() (*BluetoothLEPreferredConnectionParameters, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Bluetooth.BluetoothLEPreferredConnectionParameters", ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParametersStatics))
	if err != nil {
		return nil, err
	}
	v := (*iBluetoothLEPreferredConnectionParametersStatics)(unsafe.Pointer(inspectable))

	var out *BluetoothLEPreferredConnectionParameters
	hr, _, _ := syscall.SyscallN(
		v.VTable().BluetoothLEPreferredConnectionParametersGetThroughputOptimized,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out BluetoothLEPreferredConnectionParameters
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func BluetoothLEPreferredConnectionParametersGetPowerOptimized() (*BluetoothLEPreferredConnectionParameters, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Devices.Bluetooth.BluetoothLEPreferredConnectionParameters", ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParametersStatics))
	if err != nil {
		return nil, err
	}
	v := (*iBluetoothLEPreferredConnectionParametersStatics)(unsafe.Pointer(inspectable))

	var out *BluetoothLEPreferredConnectionParameters
	hr, _, _ := syscall.SyscallN(
		v.VTable().BluetoothLEPreferredConnectionParametersGetPowerOptimized,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out BluetoothLEPreferredConnectionParameters
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
