// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureBluetoothLEConnectionParameters string = "rc(Windows.Devices.Bluetooth.BluetoothLEConnectionParameters;{33cb0771-8da9-508f-a366-1ca388c929ab})"

type BluetoothLEConnectionParameters struct {
	ole.IUnknown
}

func (impl *BluetoothLEConnectionParameters) GetLinkTimeout() (uint16, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionParameters))
	defer itf.Release()
	v := (*iBluetoothLEConnectionParameters)(unsafe.Pointer(itf))
	return v.GetLinkTimeout()
}

func (impl *BluetoothLEConnectionParameters) GetConnectionLatency() (uint16, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionParameters))
	defer itf.Release()
	v := (*iBluetoothLEConnectionParameters)(unsafe.Pointer(itf))
	return v.GetConnectionLatency()
}

func (impl *BluetoothLEConnectionParameters) GetConnectionInterval() (uint16, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionParameters))
	defer itf.Release()
	v := (*iBluetoothLEConnectionParameters)(unsafe.Pointer(itf))
	return v.GetConnectionInterval()
}

const GUIDiBluetoothLEConnectionParameters string = "33cb0771-8da9-508f-a366-1ca388c929ab"
const SignatureiBluetoothLEConnectionParameters string = "{33cb0771-8da9-508f-a366-1ca388c929ab}"

type iBluetoothLEConnectionParameters struct {
	ole.IInspectable
}

type iBluetoothLEConnectionParametersVtbl struct {
	ole.IInspectableVtbl

	GetLinkTimeout        uintptr
	GetConnectionLatency  uintptr
	GetConnectionInterval uintptr
}

func (v *iBluetoothLEConnectionParameters) VTable() *iBluetoothLEConnectionParametersVtbl {
	return (*iBluetoothLEConnectionParametersVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBluetoothLEConnectionParameters) GetLinkTimeout() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLinkTimeout,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEConnectionParameters) GetConnectionLatency() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetConnectionLatency,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEConnectionParameters) GetConnectionInterval() (uint16, error) {
	var out uint16
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetConnectionInterval,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint16
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}
