// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureBluetoothLEPreferredConnectionParametersRequest string = "rc(Windows.Devices.Bluetooth.BluetoothLEPreferredConnectionParametersRequest;{8a375276-a528-5266-b661-cce6a5ff9739})"

type BluetoothLEPreferredConnectionParametersRequest struct {
	ole.IUnknown
}

func (impl *BluetoothLEPreferredConnectionParametersRequest) GetStatus() (BluetoothLEPreferredConnectionParametersRequestStatus, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBluetoothLEPreferredConnectionParametersRequest))
	defer itf.Release()
	v := (*iBluetoothLEPreferredConnectionParametersRequest)(unsafe.Pointer(itf))
	return v.GetStatus()
}

func (impl *BluetoothLEPreferredConnectionParametersRequest) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

const GUIDiBluetoothLEPreferredConnectionParametersRequest string = "8a375276-a528-5266-b661-cce6a5ff9739"
const SignatureiBluetoothLEPreferredConnectionParametersRequest string = "{8a375276-a528-5266-b661-cce6a5ff9739}"

type iBluetoothLEPreferredConnectionParametersRequest struct {
	ole.IInspectable
}

type iBluetoothLEPreferredConnectionParametersRequestVtbl struct {
	ole.IInspectableVtbl

	GetStatus uintptr
}

func (v *iBluetoothLEPreferredConnectionParametersRequest) VTable() *iBluetoothLEPreferredConnectionParametersRequestVtbl {
	return (*iBluetoothLEPreferredConnectionParametersRequestVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBluetoothLEPreferredConnectionParametersRequest) GetStatus() (BluetoothLEPreferredConnectionParametersRequestStatus, error) {
	var out BluetoothLEPreferredConnectionParametersRequestStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out BluetoothLEPreferredConnectionParametersRequestStatus
	)

	if hr != 0 {
		return BluetoothLEPreferredConnectionParametersRequestStatusUnspecified, ole.NewError(hr)
	}

	return out, nil
}
