// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package bluetooth

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureBluetoothLEConnectionPhy string = "rc(Windows.Devices.Bluetooth.BluetoothLEConnectionPhy;{781e5e48-621e-5a7e-8be6-1b9561ff63c9})"

type BluetoothLEConnectionPhy struct {
	ole.IUnknown
}

func (impl *BluetoothLEConnectionPhy) GetTransmitInfo() (*BluetoothLEConnectionPhyInfo, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionPhy))
	defer itf.Release()
	v := (*iBluetoothLEConnectionPhy)(unsafe.Pointer(itf))
	return v.GetTransmitInfo()
}

func (impl *BluetoothLEConnectionPhy) GetReceiveInfo() (*BluetoothLEConnectionPhyInfo, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiBluetoothLEConnectionPhy))
	defer itf.Release()
	v := (*iBluetoothLEConnectionPhy)(unsafe.Pointer(itf))
	return v.GetReceiveInfo()
}

const GUIDiBluetoothLEConnectionPhy string = "781e5e48-621e-5a7e-8be6-1b9561ff63c9"
const SignatureiBluetoothLEConnectionPhy string = "{781e5e48-621e-5a7e-8be6-1b9561ff63c9}"

type iBluetoothLEConnectionPhy struct {
	ole.IInspectable
}

type iBluetoothLEConnectionPhyVtbl struct {
	ole.IInspectableVtbl

	GetTransmitInfo uintptr
	GetReceiveInfo  uintptr
}

func (v *iBluetoothLEConnectionPhy) VTable() *iBluetoothLEConnectionPhyVtbl {
	return (*iBluetoothLEConnectionPhyVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iBluetoothLEConnectionPhy) GetTransmitInfo() (*BluetoothLEConnectionPhyInfo, error) {
	var out *BluetoothLEConnectionPhyInfo
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetTransmitInfo,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out BluetoothLEConnectionPhyInfo
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iBluetoothLEConnectionPhy) GetReceiveInfo() (*BluetoothLEConnectionPhyInfo, error) {
	var out *BluetoothLEConnectionPhyInfo
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetReceiveInfo,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out BluetoothLEConnectionPhyInfo
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
