// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package genericattributeprofile

type GattClientCharacteristicConfigurationDescriptorValue int32

const SignatureGattClientCharacteristicConfigurationDescriptorValue string = "enum(Windows.Devices.Bluetooth.GenericAttributeProfile.GattClientCharacteristicConfigurationDescriptorValue;i4)"

const (
	GattClientCharacteristicConfigurationDescriptorValueNone     GattClientCharacteristicConfigurationDescriptorValue = 0
	GattClientCharacteristicConfigurationDescriptorValueNotify   GattClientCharacteristicConfigurationDescriptorValue = 1
	GattClientCharacteristicConfigurationDescriptorValueIndicate GattClientCharacteristicConfigurationDescriptorValue = 2
)
