// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package genericattributeprofile

type GattServiceProviderAdvertisementStatus int32

const SignatureGattServiceProviderAdvertisementStatus string = "enum(Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceProviderAdvertisementStatus;i4)"

const (
	GattServiceProviderAdvertisementStatusCreated                            GattServiceProviderAdvertisementStatus = 0
	GattServiceProviderAdvertisementStatusStopped                            GattServiceProviderAdvertisementStatus = 1
	GattServiceProviderAdvertisementStatusStarted                            GattServiceProviderAdvertisementStatus = 2
	GattServiceProviderAdvertisementStatusAborted                            GattServiceProviderAdvertisementStatus = 3
	GattServiceProviderAdvertisementStatusStartedWithoutAllAdvertisementData GattServiceProviderAdvertisementStatus = 4
)
