// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint
package genericattributeprofile

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureGattCharacteristic string = "rc(Windows.Devices.Bluetooth.GenericAttributeProfile.GattCharacteristic;{59cb50c1-5934-4f68-a198-eb864fa44e6b})"

type GattCharacteristic struct {
	ole.IUnknown
}

func (impl *GattCharacteristic) GetCharacteristicProperties() (GattCharacteristicProperties, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGattCharacteristic))
	defer itf.Release()
	v := (*iGattCharacteristic)(unsafe.Pointer(itf))
	return v.GetCharacteristicProperties()
}

func (impl *GattCharacteristic) GetUuid() (syscall.GUID, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGattCharacteristic))
	defer itf.Release()
	v := (*iGattCharacteristic)(unsafe.Pointer(itf))
	return v.GetUuid()
}

const GUIDiGattCharacteristic string = "59cb50c1-5934-4f68-a198-eb864fa44e6b"
const SignatureiGattCharacteristic string = "{59cb50c1-5934-4f68-a198-eb864fa44e6b}"

type iGattCharacteristic struct {
	ole.IInspectable
}

type iGattCharacteristicVtbl struct {
	ole.IInspectableVtbl

	GetDescriptors                                        uintptr
	GetCharacteristicProperties                           uintptr
	GetProtectionLevel                                    uintptr
	SetProtectionLevel                                    uintptr
	GetUserDescription                                    uintptr
	GetUuid                                               uintptr
	GetAttributeHandle                                    uintptr
	GetPresentationFormats                                uintptr
	ReadValueAsync                                        uintptr
	ReadValueWithCacheModeAsync                           uintptr
	WriteValueAsync                                       uintptr
	WriteValueWithOptionAsync                             uintptr
	ReadClientCharacteristicConfigurationDescriptorAsync  uintptr
	WriteClientCharacteristicConfigurationDescriptorAsync uintptr
	AddValueChanged                                       uintptr
	RemoveValueChanged                                    uintptr
}

func (v *iGattCharacteristic) VTable() *iGattCharacteristicVtbl {
	return (*iGattCharacteristicVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGattCharacteristic) GetCharacteristicProperties() (GattCharacteristicProperties, error) {
	var out GattCharacteristicProperties
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCharacteristicProperties,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out GattCharacteristicProperties
	)

	if hr != 0 {
		return GattCharacteristicPropertiesNone, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGattCharacteristic) GetUuid() (syscall.GUID, error) {
	var out syscall.GUID
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetUuid,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out syscall.GUID
	)

	if hr != 0 {
		return syscall.GUID{}, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiGattCharacteristic2 string = "ae1ab578-ec06-4764-b780-9835a1d35d6e"
const SignatureiGattCharacteristic2 string = "{ae1ab578-ec06-4764-b780-9835a1d35d6e}"

type iGattCharacteristic2 struct {
	ole.IInspectable
}

type iGattCharacteristic2Vtbl struct {
	ole.IInspectableVtbl

	GetService        uintptr
	GetAllDescriptors uintptr
}

func (v *iGattCharacteristic2) VTable() *iGattCharacteristic2Vtbl {
	return (*iGattCharacteristic2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiGattCharacteristic3 string = "3f3c663e-93d4-406b-b817-db81f8ed53b3"
const SignatureiGattCharacteristic3 string = "{3f3c663e-93d4-406b-b817-db81f8ed53b3}"

type iGattCharacteristic3 struct {
	ole.IInspectable
}

type iGattCharacteristic3Vtbl struct {
	ole.IInspectableVtbl

	GetDescriptorsAsync                                             uintptr
	GetDescriptorsWithCacheModeAsync                                uintptr
	GetDescriptorsForUuidAsync                                      uintptr
	GetDescriptorsForUuidWithCacheModeAsync                         uintptr
	WriteValueWithResultAsync                                       uintptr
	WriteValueWithResultAndOptionAsync                              uintptr
	WriteClientCharacteristicConfigurationDescriptorWithResultAsync uintptr
}

func (v *iGattCharacteristic3) VTable() *iGattCharacteristic3Vtbl {
	return (*iGattCharacteristic3Vtbl)(unsafe.Pointer(v.RawVTable))
}
