// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package genericattributeprofile

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/devices/bluetooth"
)

const SignatureGattSessionStatusChangedEventArgs string = "rc(Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatusChangedEventArgs;{7605b72e-837f-404c-ab34-3163f39ddf32})"

type GattSessionStatusChangedEventArgs struct {
	ole.IUnknown
}

func (impl *GattSessionStatusChangedEventArgs) GetError() (bluetooth.BluetoothError, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGattSessionStatusChangedEventArgs))
	defer itf.Release()
	v := (*iGattSessionStatusChangedEventArgs)(unsafe.Pointer(itf))
	return v.GetError()
}

func (impl *GattSessionStatusChangedEventArgs) GetStatus() (GattSessionStatus, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGattSessionStatusChangedEventArgs))
	defer itf.Release()
	v := (*iGattSessionStatusChangedEventArgs)(unsafe.Pointer(itf))
	return v.GetStatus()
}

const GUIDiGattSessionStatusChangedEventArgs string = "7605b72e-837f-404c-ab34-3163f39ddf32"
const SignatureiGattSessionStatusChangedEventArgs string = "{7605b72e-837f-404c-ab34-3163f39ddf32}"

type iGattSessionStatusChangedEventArgs struct {
	ole.IInspectable
}

type iGattSessionStatusChangedEventArgsVtbl struct {
	ole.IInspectableVtbl

	GetError  uintptr
	GetStatus uintptr
}

func (v *iGattSessionStatusChangedEventArgs) VTable() *iGattSessionStatusChangedEventArgsVtbl {
	return (*iGattSessionStatusChangedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGattSessionStatusChangedEventArgs) GetError() (bluetooth.BluetoothError, error) {
	var out bluetooth.BluetoothError
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetError,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bluetooth.BluetoothError
	)

	if hr != 0 {
		return bluetooth.BluetoothErrorSuccess, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGattSessionStatusChangedEventArgs) GetStatus() (GattSessionStatus, error) {
	var out GattSessionStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out GattSessionStatus
	)

	if hr != 0 {
		return GattSessionStatusClosed, ole.NewError(hr)
	}

	return out, nil
}
