// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package genericattributeprofile

type GattRequestState int32

const SignatureGattRequestState string = "enum(Windows.Devices.Bluetooth.GenericAttributeProfile.GattRequestState;i4)"

const (
	GattRequestStatePending   GattRequestState = 0
	GattRequestStateCompleted GattRequestState = 1
	GattRequestStateCanceled  GattRequestState = 2
)
