// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package genericattributeprofile

type GattSessionStatus int32

const SignatureGattSessionStatus string = "enum(Windows.Devices.Bluetooth.GenericAttributeProfile.GattSessionStatus;i4)"

const (
	GattSessionStatusClosed GattSessionStatus = 0
	GattSessionStatusActive GattSessionStatus = 1
)
