// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type StorageProviderProtectionMode int32

const SignatureStorageProviderProtectionMode string = "enum(Windows.Storage.Provider.StorageProviderProtectionMode;i4)"

const (
	StorageProviderProtectionModeUnknown  StorageProviderProtectionMode = 0
	StorageProviderProtectionModePersonal StorageProviderProtectionMode = 1
)
