// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type StorageProviderInSyncPolicy uint32

const SignatureStorageProviderInSyncPolicy string = "enum(Windows.Storage.Provider.StorageProviderInSyncPolicy;u4)"

const (
	StorageProviderInSyncPolicyDefault                     StorageProviderInSyncPolicy = 0
	StorageProviderInSyncPolicyFileCreationTime            StorageProviderInSyncPolicy = 1
	StorageProviderInSyncPolicyFileReadOnlyAttribute       StorageProviderInSyncPolicy = 2
	StorageProviderInSyncPolicyFileHiddenAttribute         StorageProviderInSyncPolicy = 4
	StorageProviderInSyncPolicyFileSystemAttribute         StorageProviderInSyncPolicy = 8
	StorageProviderInSyncPolicyDirectoryCreationTime       StorageProviderInSyncPolicy = 16
	StorageProviderInSyncPolicyDirectoryReadOnlyAttribute  StorageProviderInSyncPolicy = 32
	StorageProviderInSyncPolicyDirectoryHiddenAttribute    StorageProviderInSyncPolicy = 64
	StorageProviderInSyncPolicyDirectorySystemAttribute    StorageProviderInSyncPolicy = 128
	StorageProviderInSyncPolicyFileLastWriteTime           StorageProviderInSyncPolicy = 256
	StorageProviderInSyncPolicyDirectoryLastWriteTime      StorageProviderInSyncPolicy = 512
	StorageProviderInSyncPolicyPreserveInsyncForSyncEngine StorageProviderInSyncPolicy = 2147483648
)
