// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type StorageProviderHydrationPolicyModifier uint32

const SignatureStorageProviderHydrationPolicyModifier string = "enum(Windows.Storage.Provider.StorageProviderHydrationPolicyModifier;u4)"

const (
	StorageProviderHydrationPolicyModifierNone                      StorageProviderHydrationPolicyModifier = 0
	StorageProviderHydrationPolicyModifierValidationRequired        StorageProviderHydrationPolicyModifier = 1
	StorageProviderHydrationPolicyModifierStreamingAllowed          StorageProviderHydrationPolicyModifier = 2
	StorageProviderHydrationPolicyModifierAutoDehydrationAllowed    StorageProviderHydrationPolicyModifier = 4
	StorageProviderHydrationPolicyModifierAllowFullRestartHydration StorageProviderHydrationPolicyModifier = 8
)
