// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type StorageProviderHardlinkPolicy uint32

const SignatureStorageProviderHardlinkPolicy string = "enum(Windows.Storage.Provider.StorageProviderHardlinkPolicy;u4)"

const (
	StorageProviderHardlinkPolicyNone    StorageProviderHardlinkPolicy = 0
	StorageProviderHardlinkPolicyAllowed StorageProviderHardlinkPolicy = 1
)
