// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureStorageProviderItemProperty string = "rc(Windows.Storage.Provider.StorageProviderItemProperty;{476cb558-730b-4188-b7b5-63b716ed476d})"

type StorageProviderItemProperty struct {
	ole.IUnknown
}

func NewStorageProviderItemProperty() (*StorageProviderItemProperty, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Storage.Provider.StorageProviderItemProperty")
	if err != nil {
		return nil, err
	}
	return (*StorageProviderItemProperty)(unsafe.Pointer(inspectable)), nil
}

func (impl *StorageProviderItemProperty) SetId(value int32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemProperty))
	defer itf.Release()
	v := (*iStorageProviderItemProperty)(unsafe.Pointer(itf))
	return v.SetId(value)
}

func (impl *StorageProviderItemProperty) GetId() (int32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemProperty))
	defer itf.Release()
	v := (*iStorageProviderItemProperty)(unsafe.Pointer(itf))
	return v.GetId()
}

func (impl *StorageProviderItemProperty) SetValue(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemProperty))
	defer itf.Release()
	v := (*iStorageProviderItemProperty)(unsafe.Pointer(itf))
	return v.SetValue(value)
}

func (impl *StorageProviderItemProperty) GetValue() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemProperty))
	defer itf.Release()
	v := (*iStorageProviderItemProperty)(unsafe.Pointer(itf))
	return v.GetValue()
}

func (impl *StorageProviderItemProperty) SetIconResource(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemProperty))
	defer itf.Release()
	v := (*iStorageProviderItemProperty)(unsafe.Pointer(itf))
	return v.SetIconResource(value)
}

func (impl *StorageProviderItemProperty) GetIconResource() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemProperty))
	defer itf.Release()
	v := (*iStorageProviderItemProperty)(unsafe.Pointer(itf))
	return v.GetIconResource()
}

const GUIDiStorageProviderItemProperty string = "476cb558-730b-4188-b7b5-63b716ed476d"
const SignatureiStorageProviderItemProperty string = "{476cb558-730b-4188-b7b5-63b716ed476d}"

type iStorageProviderItemProperty struct {
	ole.IInspectable
}

type iStorageProviderItemPropertyVtbl struct {
	ole.IInspectableVtbl

	SetId           uintptr
	GetId           uintptr
	SetValue        uintptr
	GetValue        uintptr
	SetIconResource uintptr
	GetIconResource uintptr
}

func (v *iStorageProviderItemProperty) VTable() *iStorageProviderItemPropertyVtbl {
	return (*iStorageProviderItemPropertyVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderItemProperty) SetId(value int32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetId,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in int32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderItemProperty) GetId() (int32, error) {
	var out int32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetId,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderItemProperty) SetValue(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetValue,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderItemProperty) GetValue() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetValue,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderItemProperty) SetIconResource(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetIconResource,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderItemProperty) GetIconResource() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIconResource,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
