// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
	"github.com/saltosystems/winrt-go/windows/storage"
	"github.com/saltosystems/winrt-go/windows/storage/streams"
)

const SignatureStorageProviderSyncRootInfo string = "rc(Windows.Storage.Provider.StorageProviderSyncRootInfo;{7c1305c4-99f9-41ac-8904-ab055d654926})"

type StorageProviderSyncRootInfo struct {
	ole.IUnknown
}

func NewStorageProviderSyncRootInfo() (*StorageProviderSyncRootInfo, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Storage.Provider.StorageProviderSyncRootInfo")
	if err != nil {
		return nil, err
	}
	return (*StorageProviderSyncRootInfo)(unsafe.Pointer(inspectable)), nil
}

func (impl *StorageProviderSyncRootInfo) GetId() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetId()
}

func (impl *StorageProviderSyncRootInfo) SetId(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetId(value)
}

func (impl *StorageProviderSyncRootInfo) GetContext() (*streams.IBuffer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetContext()
}

func (impl *StorageProviderSyncRootInfo) SetContext(value *streams.IBuffer) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetContext(value)
}

func (impl *StorageProviderSyncRootInfo) GetPath() (*storage.IStorageFolder, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetPath()
}

func (impl *StorageProviderSyncRootInfo) SetPath(value *storage.IStorageFolder) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetPath(value)
}

func (impl *StorageProviderSyncRootInfo) GetDisplayNameResource() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetDisplayNameResource()
}

func (impl *StorageProviderSyncRootInfo) SetDisplayNameResource(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetDisplayNameResource(value)
}

func (impl *StorageProviderSyncRootInfo) GetIconResource() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetIconResource()
}

func (impl *StorageProviderSyncRootInfo) SetIconResource(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetIconResource(value)
}

func (impl *StorageProviderSyncRootInfo) GetHydrationPolicy() (StorageProviderHydrationPolicy, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetHydrationPolicy()
}

func (impl *StorageProviderSyncRootInfo) SetHydrationPolicy(value StorageProviderHydrationPolicy) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetHydrationPolicy(value)
}

func (impl *StorageProviderSyncRootInfo) GetHydrationPolicyModifier() (StorageProviderHydrationPolicyModifier, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetHydrationPolicyModifier()
}

func (impl *StorageProviderSyncRootInfo) SetHydrationPolicyModifier(value StorageProviderHydrationPolicyModifier) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetHydrationPolicyModifier(value)
}

func (impl *StorageProviderSyncRootInfo) GetPopulationPolicy() (StorageProviderPopulationPolicy, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetPopulationPolicy()
}

func (impl *StorageProviderSyncRootInfo) SetPopulationPolicy(value StorageProviderPopulationPolicy) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetPopulationPolicy(value)
}

func (impl *StorageProviderSyncRootInfo) GetInSyncPolicy() (StorageProviderInSyncPolicy, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetInSyncPolicy()
}

func (impl *StorageProviderSyncRootInfo) SetInSyncPolicy(value StorageProviderInSyncPolicy) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetInSyncPolicy(value)
}

func (impl *StorageProviderSyncRootInfo) GetHardlinkPolicy() (StorageProviderHardlinkPolicy, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetHardlinkPolicy()
}

func (impl *StorageProviderSyncRootInfo) SetHardlinkPolicy(value StorageProviderHardlinkPolicy) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetHardlinkPolicy(value)
}

func (impl *StorageProviderSyncRootInfo) GetShowSiblingsAsGroup() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetShowSiblingsAsGroup()
}

func (impl *StorageProviderSyncRootInfo) SetShowSiblingsAsGroup(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetShowSiblingsAsGroup(value)
}

func (impl *StorageProviderSyncRootInfo) GetVersion() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetVersion()
}

func (impl *StorageProviderSyncRootInfo) SetVersion(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetVersion(value)
}

func (impl *StorageProviderSyncRootInfo) GetProtectionMode() (StorageProviderProtectionMode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetProtectionMode()
}

func (impl *StorageProviderSyncRootInfo) SetProtectionMode(value StorageProviderProtectionMode) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetProtectionMode(value)
}

func (impl *StorageProviderSyncRootInfo) GetAllowPinning() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetAllowPinning()
}

func (impl *StorageProviderSyncRootInfo) SetAllowPinning(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetAllowPinning(value)
}

func (impl *StorageProviderSyncRootInfo) GetStorageProviderItemPropertyDefinitions() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetStorageProviderItemPropertyDefinitions()
}

func (impl *StorageProviderSyncRootInfo) GetRecycleBinUri() (*foundation.Uri, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.GetRecycleBinUri()
}

func (impl *StorageProviderSyncRootInfo) SetRecycleBinUri(value *foundation.Uri) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo)(unsafe.Pointer(itf))
	return v.SetRecycleBinUri(value)
}

func (impl *StorageProviderSyncRootInfo) GetProviderId() (syscall.GUID, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo2))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo2)(unsafe.Pointer(itf))
	return v.GetProviderId()
}

func (impl *StorageProviderSyncRootInfo) SetProviderId(value syscall.GUID) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo2))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo2)(unsafe.Pointer(itf))
	return v.SetProviderId(value)
}

func (impl *StorageProviderSyncRootInfo) GetFallbackFileTypeInfo() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderSyncRootInfo3))
	defer itf.Release()
	v := (*iStorageProviderSyncRootInfo3)(unsafe.Pointer(itf))
	return v.GetFallbackFileTypeInfo()
}

const GUIDiStorageProviderSyncRootInfo string = "7c1305c4-99f9-41ac-8904-ab055d654926"
const SignatureiStorageProviderSyncRootInfo string = "{7c1305c4-99f9-41ac-8904-ab055d654926}"

type iStorageProviderSyncRootInfo struct {
	ole.IInspectable
}

type iStorageProviderSyncRootInfoVtbl struct {
	ole.IInspectableVtbl

	GetId                                     uintptr
	SetId                                     uintptr
	GetContext                                uintptr
	SetContext                                uintptr
	GetPath                                   uintptr
	SetPath                                   uintptr
	GetDisplayNameResource                    uintptr
	SetDisplayNameResource                    uintptr
	GetIconResource                           uintptr
	SetIconResource                           uintptr
	GetHydrationPolicy                        uintptr
	SetHydrationPolicy                        uintptr
	GetHydrationPolicyModifier                uintptr
	SetHydrationPolicyModifier                uintptr
	GetPopulationPolicy                       uintptr
	SetPopulationPolicy                       uintptr
	GetInSyncPolicy                           uintptr
	SetInSyncPolicy                           uintptr
	GetHardlinkPolicy                         uintptr
	SetHardlinkPolicy                         uintptr
	GetShowSiblingsAsGroup                    uintptr
	SetShowSiblingsAsGroup                    uintptr
	GetVersion                                uintptr
	SetVersion                                uintptr
	GetProtectionMode                         uintptr
	SetProtectionMode                         uintptr
	GetAllowPinning                           uintptr
	SetAllowPinning                           uintptr
	GetStorageProviderItemPropertyDefinitions uintptr
	GetRecycleBinUri                          uintptr
	SetRecycleBinUri                          uintptr
}

func (v *iStorageProviderSyncRootInfo) VTable() *iStorageProviderSyncRootInfoVtbl {
	return (*iStorageProviderSyncRootInfoVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderSyncRootInfo) GetId() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetId(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetId,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetContext() (*streams.IBuffer, error) {
	var out *streams.IBuffer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetContext,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out streams.IBuffer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetContext(value *streams.IBuffer) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetContext,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in streams.IBuffer
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetPath() (*storage.IStorageFolder, error) {
	var out *storage.IStorageFolder
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPath,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out storage.IStorageFolder
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetPath(value *storage.IStorageFolder) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPath,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in storage.IStorageFolder
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetDisplayNameResource() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDisplayNameResource,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetDisplayNameResource(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetDisplayNameResource,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetIconResource() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIconResource,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetIconResource(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetIconResource,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetHydrationPolicy() (StorageProviderHydrationPolicy, error) {
	var out StorageProviderHydrationPolicy
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetHydrationPolicy,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderHydrationPolicy
	)

	if hr != 0 {
		return StorageProviderHydrationPolicyPartial, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetHydrationPolicy(value StorageProviderHydrationPolicy) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetHydrationPolicy,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in StorageProviderHydrationPolicy
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetHydrationPolicyModifier() (StorageProviderHydrationPolicyModifier, error) {
	var out StorageProviderHydrationPolicyModifier
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetHydrationPolicyModifier,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderHydrationPolicyModifier
	)

	if hr != 0 {
		return StorageProviderHydrationPolicyModifierNone, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetHydrationPolicyModifier(value StorageProviderHydrationPolicyModifier) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetHydrationPolicyModifier,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in StorageProviderHydrationPolicyModifier
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetPopulationPolicy() (StorageProviderPopulationPolicy, error) {
	var out StorageProviderPopulationPolicy
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPopulationPolicy,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderPopulationPolicy
	)

	if hr != 0 {
		return StorageProviderPopulationPolicyFull, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetPopulationPolicy(value StorageProviderPopulationPolicy) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPopulationPolicy,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in StorageProviderPopulationPolicy
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetInSyncPolicy() (StorageProviderInSyncPolicy, error) {
	var out StorageProviderInSyncPolicy
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInSyncPolicy,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderInSyncPolicy
	)

	if hr != 0 {
		return StorageProviderInSyncPolicyDefault, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetInSyncPolicy(value StorageProviderInSyncPolicy) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetInSyncPolicy,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in StorageProviderInSyncPolicy
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetHardlinkPolicy() (StorageProviderHardlinkPolicy, error) {
	var out StorageProviderHardlinkPolicy
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetHardlinkPolicy,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderHardlinkPolicy
	)

	if hr != 0 {
		return StorageProviderHardlinkPolicyNone, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetHardlinkPolicy(value StorageProviderHardlinkPolicy) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetHardlinkPolicy,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in StorageProviderHardlinkPolicy
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetShowSiblingsAsGroup() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetShowSiblingsAsGroup,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetShowSiblingsAsGroup(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetShowSiblingsAsGroup,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetVersion() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetVersion,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetVersion(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetVersion,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetProtectionMode() (StorageProviderProtectionMode, error) {
	var out StorageProviderProtectionMode
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProtectionMode,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderProtectionMode
	)

	if hr != 0 {
		return StorageProviderProtectionModeUnknown, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetProtectionMode(value StorageProviderProtectionMode) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetProtectionMode,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in StorageProviderProtectionMode
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetAllowPinning() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetAllowPinning,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetAllowPinning(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetAllowPinning,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderSyncRootInfo) GetStorageProviderItemPropertyDefinitions() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStorageProviderItemPropertyDefinitions,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) GetRecycleBinUri() (*foundation.Uri, error) {
	var out *foundation.Uri
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRecycleBinUri,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.Uri
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo) SetRecycleBinUri(value *foundation.Uri) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetRecycleBinUri,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in foundation.Uri
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStorageProviderSyncRootInfo2 string = "cf51b023-7cf1-5166-bdba-efd95f529e31"
const SignatureiStorageProviderSyncRootInfo2 string = "{cf51b023-7cf1-5166-bdba-efd95f529e31}"

type iStorageProviderSyncRootInfo2 struct {
	ole.IInspectable
}

type iStorageProviderSyncRootInfo2Vtbl struct {
	ole.IInspectableVtbl

	GetProviderId uintptr
	SetProviderId uintptr
}

func (v *iStorageProviderSyncRootInfo2) VTable() *iStorageProviderSyncRootInfo2Vtbl {
	return (*iStorageProviderSyncRootInfo2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderSyncRootInfo2) GetProviderId() (syscall.GUID, error) {
	var out syscall.GUID
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProviderId,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out syscall.GUID
	)

	if hr != 0 {
		return syscall.GUID{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderSyncRootInfo2) SetProviderId(value syscall.GUID) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetProviderId,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&value)), // in syscall.GUID
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStorageProviderSyncRootInfo3 string = "507a6617-bef6-56fd-855e-75ace2e45cf5"
const SignatureiStorageProviderSyncRootInfo3 string = "{507a6617-bef6-56fd-855e-75ace2e45cf5}"

type iStorageProviderSyncRootInfo3 struct {
	ole.IInspectable
}

type iStorageProviderSyncRootInfo3Vtbl struct {
	ole.IInspectableVtbl

	GetFallbackFileTypeInfo uintptr
}

func (v *iStorageProviderSyncRootInfo3) VTable() *iStorageProviderSyncRootInfo3Vtbl {
	return (*iStorageProviderSyncRootInfo3Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderSyncRootInfo3) GetFallbackFileTypeInfo() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetFallbackFileTypeInfo,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
