// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type StorageProviderPopulationPolicy int32

const SignatureStorageProviderPopulationPolicy string = "enum(Windows.Storage.Provider.StorageProviderPopulationPolicy;i4)"

const (
	StorageProviderPopulationPolicyFull       StorageProviderPopulationPolicy = 1
	StorageProviderPopulationPolicyAlwaysFull StorageProviderPopulationPolicy = 2
)
