// Code generated by winrt-go-gen. DO NOT EDIT.

//nolint
package winrt

import (
	"github.com/go-ole/go-ole"
	"syscall"
	"unsafe"
)

type IBuffer struct {
	ole.IInspectable
}

type IBufferVtbl struct {
	ole.IInspectableVtbl

	GetCapacity uintptr
	GetLength   uintptr
	SetLength   uintptr
}
