// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package foundation

type PropertyType int32

const SignaturePropertyType string = "enum(Windows.Foundation.PropertyType;i4)"

const (
	PropertyTypeEmpty            PropertyType = 0
	PropertyTypeUInt8            PropertyType = 1
	PropertyTypeInt16            PropertyType = 2
	PropertyTypeUInt16           PropertyType = 3
	PropertyTypeInt32            PropertyType = 4
	PropertyTypeUInt32           PropertyType = 5
	PropertyTypeInt64            PropertyType = 6
	PropertyTypeUInt64           PropertyType = 7
	PropertyTypeSingle           PropertyType = 8
	PropertyTypeDouble           PropertyType = 9
	PropertyTypeChar16           PropertyType = 10
	PropertyTypeBoolean          PropertyType = 11
	PropertyTypeString           PropertyType = 12
	PropertyTypeInspectable      PropertyType = 13
	PropertyTypeDateTime         PropertyType = 14
	PropertyTypeTimeSpan         PropertyType = 15
	PropertyTypeGuid             PropertyType = 16
	PropertyTypePoint            PropertyType = 17
	PropertyTypeSize             PropertyType = 18
	PropertyTypeRect             PropertyType = 19
	PropertyTypeOtherType        PropertyType = 20
	PropertyTypeUInt8Array       PropertyType = 1025
	PropertyTypeInt16Array       PropertyType = 1026
	PropertyTypeUInt16Array      PropertyType = 1027
	PropertyTypeInt32Array       PropertyType = 1028
	PropertyTypeUInt32Array      PropertyType = 1029
	PropertyTypeInt64Array       PropertyType = 1030
	PropertyTypeUInt64Array      PropertyType = 1031
	PropertyTypeSingleArray      PropertyType = 1032
	PropertyTypeDoubleArray      PropertyType = 1033
	PropertyTypeChar16Array      PropertyType = 1034
	PropertyTypeBooleanArray     PropertyType = 1035
	PropertyTypeStringArray      PropertyType = 1036
	PropertyTypeInspectableArray PropertyType = 1037
	PropertyTypeDateTimeArray    PropertyType = 1038
	PropertyTypeTimeSpanArray    PropertyType = 1039
	PropertyTypeGuidArray        PropertyType = 1040
	PropertyTypePointArray       PropertyType = 1041
	PropertyTypeSizeArray        PropertyType = 1042
	PropertyTypeRectArray        PropertyType = 1043
	PropertyTypeOtherTypeArray   PropertyType = 1044
)
