// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint
package foundation

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

/*
#include <stddef.h>
*/
import "C"

//export winrt_TypedEventHandler_QueryInterface
func winrt_TypedEventHandler_QueryInterface(instancePtr, iidPtr unsafe.Pointer, ppvObject *unsafe.Pointer) uintptr {
	// This function must adhere to the QueryInterface defined here:
	// https://docs.microsoft.com/en-us/windows/win32/api/unknwn/nn-unknwn-iunknown
	iid := (*ole.GUID)(iidPtr)
	instance := (*TypedEventHandler)(instancePtr)
	if ole.IsEqualGUID(iid, instance.IID) {
		// This is us.
		*ppvObject = instancePtr
		return ole.S_OK
	}
	if ole.IsEqualGUID(iid, ole.IID_IUnknown) {
		// This is our parent. There are some limitations as to what we can
		// return here, but returning the *TypedEventHandler pointer is fine.
		*ppvObject = instancePtr
		return ole.S_OK
	}
	return 0x80004002 // E_NOTINTERFACE
}

//export winrt_TypedEventHandler_Invoke
func winrt_TypedEventHandler_Invoke(instancePtr, senderPtr, argsPtr unsafe.Pointer) uintptr {
	// See the quote above.
	instance := (*TypedEventHandler)(instancePtr)
	instance.Callback(instance, senderPtr, argsPtr)
	return ole.S_OK
}
