// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/media"
)

const SignatureGlobalSystemMediaTransportControlsSession string = "rc(Windows.Media.Control.GlobalSystemMediaTransportControlsSession;{7148c835-9b14-5ae2-ab85-dc9b1c14e1a8})"

type GlobalSystemMediaTransportControlsSession struct {
	ole.IUnknown
}

func (impl *GlobalSystemMediaTransportControlsSession) GetSourceAppUserModelId() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.GetSourceAppUserModelId()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryGetMediaPropertiesAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryGetMediaPropertiesAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) GetTimelineProperties() (*GlobalSystemMediaTransportControlsSessionTimelineProperties, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.GetTimelineProperties()
}

func (impl *GlobalSystemMediaTransportControlsSession) GetPlaybackInfo() (*GlobalSystemMediaTransportControlsSessionPlaybackInfo, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.GetPlaybackInfo()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryPlayAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryPlayAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryPauseAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryPauseAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryStopAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryStopAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryRecordAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryRecordAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryFastForwardAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryFastForwardAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryRewindAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryRewindAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TrySkipNextAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TrySkipNextAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TrySkipPreviousAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TrySkipPreviousAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryChangeChannelUpAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryChangeChannelUpAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryChangeChannelDownAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryChangeChannelDownAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryTogglePlayPauseAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryTogglePlayPauseAsync()
}

func (impl *GlobalSystemMediaTransportControlsSession) TryChangeAutoRepeatModeAsync(requestedAutoRepeatMode media.MediaPlaybackAutoRepeatMode) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryChangeAutoRepeatModeAsync(requestedAutoRepeatMode)
}

func (impl *GlobalSystemMediaTransportControlsSession) TryChangePlaybackRateAsync(requestedPlaybackRate float64) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryChangePlaybackRateAsync(requestedPlaybackRate)
}

func (impl *GlobalSystemMediaTransportControlsSession) TryChangeShuffleActiveAsync(requestedShuffleState bool) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryChangeShuffleActiveAsync(requestedShuffleState)
}

func (impl *GlobalSystemMediaTransportControlsSession) TryChangePlaybackPositionAsync(requestedPlaybackPosition int64) (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryChangePlaybackPositionAsync(requestedPlaybackPosition)
}

func (impl *GlobalSystemMediaTransportControlsSession) AddTimelinePropertiesChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.AddTimelinePropertiesChanged(handler)
}

func (impl *GlobalSystemMediaTransportControlsSession) RemoveTimelinePropertiesChanged(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.RemoveTimelinePropertiesChanged(token)
}

func (impl *GlobalSystemMediaTransportControlsSession) AddPlaybackInfoChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.AddPlaybackInfoChanged(handler)
}

func (impl *GlobalSystemMediaTransportControlsSession) RemovePlaybackInfoChanged(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.RemovePlaybackInfoChanged(token)
}

func (impl *GlobalSystemMediaTransportControlsSession) AddMediaPropertiesChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.AddMediaPropertiesChanged(handler)
}

func (impl *GlobalSystemMediaTransportControlsSession) RemoveMediaPropertiesChanged(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.RemoveMediaPropertiesChanged(token)
}

const GUIDiGlobalSystemMediaTransportControlsSession string = "7148c835-9b14-5ae2-ab85-dc9b1c14e1a8"
const SignatureiGlobalSystemMediaTransportControlsSession string = "{7148c835-9b14-5ae2-ab85-dc9b1c14e1a8}"

type iGlobalSystemMediaTransportControlsSession struct {
	ole.IInspectable
}

type iGlobalSystemMediaTransportControlsSessionVtbl struct {
	ole.IInspectableVtbl

	GetSourceAppUserModelId         uintptr
	TryGetMediaPropertiesAsync      uintptr
	GetTimelineProperties           uintptr
	GetPlaybackInfo                 uintptr
	TryPlayAsync                    uintptr
	TryPauseAsync                   uintptr
	TryStopAsync                    uintptr
	TryRecordAsync                  uintptr
	TryFastForwardAsync             uintptr
	TryRewindAsync                  uintptr
	TrySkipNextAsync                uintptr
	TrySkipPreviousAsync            uintptr
	TryChangeChannelUpAsync         uintptr
	TryChangeChannelDownAsync       uintptr
	TryTogglePlayPauseAsync         uintptr
	TryChangeAutoRepeatModeAsync    uintptr
	TryChangePlaybackRateAsync      uintptr
	TryChangeShuffleActiveAsync     uintptr
	TryChangePlaybackPositionAsync  uintptr
	AddTimelinePropertiesChanged    uintptr
	RemoveTimelinePropertiesChanged uintptr
	AddPlaybackInfoChanged          uintptr
	RemovePlaybackInfoChanged       uintptr
	AddMediaPropertiesChanged       uintptr
	RemoveMediaPropertiesChanged    uintptr
}

func (v *iGlobalSystemMediaTransportControlsSession) VTable() *iGlobalSystemMediaTransportControlsSessionVtbl {
	return (*iGlobalSystemMediaTransportControlsSessionVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGlobalSystemMediaTransportControlsSession) GetSourceAppUserModelId() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSourceAppUserModelId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryGetMediaPropertiesAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryGetMediaPropertiesAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) GetTimelineProperties() (*GlobalSystemMediaTransportControlsSessionTimelineProperties, error) {
	var out *GlobalSystemMediaTransportControlsSessionTimelineProperties
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetTimelineProperties,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out GlobalSystemMediaTransportControlsSessionTimelineProperties
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) GetPlaybackInfo() (*GlobalSystemMediaTransportControlsSessionPlaybackInfo, error) {
	var out *GlobalSystemMediaTransportControlsSessionPlaybackInfo
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPlaybackInfo,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out GlobalSystemMediaTransportControlsSessionPlaybackInfo
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryPlayAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryPlayAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryPauseAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryPauseAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryStopAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryStopAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryRecordAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryRecordAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryFastForwardAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryFastForwardAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryRewindAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryRewindAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TrySkipNextAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TrySkipNextAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TrySkipPreviousAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TrySkipPreviousAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryChangeChannelUpAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryChangeChannelUpAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryChangeChannelDownAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryChangeChannelDownAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryTogglePlayPauseAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryTogglePlayPauseAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryChangeAutoRepeatModeAsync(requestedAutoRepeatMode media.MediaPlaybackAutoRepeatMode) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryChangeAutoRepeatModeAsync,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(requestedAutoRepeatMode), // in media.MediaPlaybackAutoRepeatMode
		uintptr(unsafe.Pointer(&out)),    // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryChangePlaybackRateAsync(requestedPlaybackRate float64) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryChangePlaybackRateAsync,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(requestedPlaybackRate), // in float64
		uintptr(unsafe.Pointer(&out)),  // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryChangeShuffleActiveAsync(requestedShuffleState bool) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryChangeShuffleActiveAsync,
		uintptr(unsafe.Pointer(v)),                                // this
		uintptr(*(*byte)(unsafe.Pointer(&requestedShuffleState))), // in bool
		uintptr(unsafe.Pointer(&out)),                             // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) TryChangePlaybackPositionAsync(requestedPlaybackPosition int64) (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryChangePlaybackPositionAsync,
		uintptr(unsafe.Pointer(v)),         // this
		uintptr(requestedPlaybackPosition), // in int64
		uintptr(unsafe.Pointer(&out)),      // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) AddTimelinePropertiesChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddTimelinePropertiesChanged,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) RemoveTimelinePropertiesChanged(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveTimelinePropertiesChanged,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iGlobalSystemMediaTransportControlsSession) AddPlaybackInfoChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddPlaybackInfoChanged,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) RemovePlaybackInfoChanged(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemovePlaybackInfoChanged,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iGlobalSystemMediaTransportControlsSession) AddMediaPropertiesChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddMediaPropertiesChanged,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iGlobalSystemMediaTransportControlsSession) RemoveMediaPropertiesChanged(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveMediaPropertiesChanged,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
