// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureGlobalSystemMediaTransportControlsSessionManager string = "rc(Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager;{cace8eac-e86e-504a-ab31-5ff8ff1bce49})"

type GlobalSystemMediaTransportControlsSessionManager struct {
	ole.IUnknown
}

func (impl *GlobalSystemMediaTransportControlsSessionManager) GetCurrentSession() (*GlobalSystemMediaTransportControlsSession, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSessionManager))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSessionManager)(unsafe.Pointer(itf))
	return v.GetCurrentSession()
}

const GUIDiGlobalSystemMediaTransportControlsSessionManager string = "cace8eac-e86e-504a-ab31-5ff8ff1bce49"
const SignatureiGlobalSystemMediaTransportControlsSessionManager string = "{cace8eac-e86e-504a-ab31-5ff8ff1bce49}"

type iGlobalSystemMediaTransportControlsSessionManager struct {
	ole.IInspectable
}

type iGlobalSystemMediaTransportControlsSessionManagerVtbl struct {
	ole.IInspectableVtbl

	GetCurrentSession           uintptr
	GetSessions                 uintptr
	AddCurrentSessionChanged    uintptr
	RemoveCurrentSessionChanged uintptr
	AddSessionsChanged          uintptr
	RemoveSessionsChanged       uintptr
}

func (v *iGlobalSystemMediaTransportControlsSessionManager) VTable() *iGlobalSystemMediaTransportControlsSessionManagerVtbl {
	return (*iGlobalSystemMediaTransportControlsSessionManagerVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGlobalSystemMediaTransportControlsSessionManager) GetCurrentSession() (*GlobalSystemMediaTransportControlsSession, error) {
	var out *GlobalSystemMediaTransportControlsSession
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCurrentSession,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out GlobalSystemMediaTransportControlsSession
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiGlobalSystemMediaTransportControlsSessionManagerStatics string = "2050c4ee-11a0-57de-aed7-c97c70338245"
const SignatureiGlobalSystemMediaTransportControlsSessionManagerStatics string = "{2050c4ee-11a0-57de-aed7-c97c70338245}"

type iGlobalSystemMediaTransportControlsSessionManagerStatics struct {
	ole.IInspectable
}

type iGlobalSystemMediaTransportControlsSessionManagerStaticsVtbl struct {
	ole.IInspectableVtbl

	GlobalSystemMediaTransportControlsSessionManagerRequestAsync uintptr
}

func (v *iGlobalSystemMediaTransportControlsSessionManagerStatics) VTable() *iGlobalSystemMediaTransportControlsSessionManagerStaticsVtbl {
	return (*iGlobalSystemMediaTransportControlsSessionManagerStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func GlobalSystemMediaTransportControlsSessionManagerRequestAsync() (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Media.Control.GlobalSystemMediaTransportControlsSessionManager", ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSessionManagerStatics))
	if err != nil {
		return nil, err
	}
	v := (*iGlobalSystemMediaTransportControlsSessionManagerStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().GlobalSystemMediaTransportControlsSessionManagerRequestAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
