// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureGlobalSystemMediaTransportControlsSession string = "rc(Windows.Media.Control.GlobalSystemMediaTransportControlsSession;{7148c835-9b14-5ae2-ab85-dc9b1c14e1a8})"

type GlobalSystemMediaTransportControlsSession struct {
	ole.IUnknown
}

func (impl *GlobalSystemMediaTransportControlsSession) TryGetMediaPropertiesAsync() (*foundation.IAsyncOperation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiGlobalSystemMediaTransportControlsSession))
	defer itf.Release()
	v := (*iGlobalSystemMediaTransportControlsSession)(unsafe.Pointer(itf))
	return v.TryGetMediaPropertiesAsync()
}

const GUIDiGlobalSystemMediaTransportControlsSession string = "7148c835-9b14-5ae2-ab85-dc9b1c14e1a8"
const SignatureiGlobalSystemMediaTransportControlsSession string = "{7148c835-9b14-5ae2-ab85-dc9b1c14e1a8}"

type iGlobalSystemMediaTransportControlsSession struct {
	ole.IInspectable
}

type iGlobalSystemMediaTransportControlsSessionVtbl struct {
	ole.IInspectableVtbl

	GetSourceAppUserModelId         uintptr
	TryGetMediaPropertiesAsync      uintptr
	GetTimelineProperties           uintptr
	GetPlaybackInfo                 uintptr
	TryPlayAsync                    uintptr
	TryPauseAsync                   uintptr
	TryStopAsync                    uintptr
	TryRecordAsync                  uintptr
	TryFastForwardAsync             uintptr
	TryRewindAsync                  uintptr
	TrySkipNextAsync                uintptr
	TrySkipPreviousAsync            uintptr
	TryChangeChannelUpAsync         uintptr
	TryChangeChannelDownAsync       uintptr
	TryTogglePlayPauseAsync         uintptr
	TryChangeAutoRepeatModeAsync    uintptr
	TryChangePlaybackRateAsync      uintptr
	TryChangeShuffleActiveAsync     uintptr
	TryChangePlaybackPositionAsync  uintptr
	AddTimelinePropertiesChanged    uintptr
	RemoveTimelinePropertiesChanged uintptr
	AddPlaybackInfoChanged          uintptr
	RemovePlaybackInfoChanged       uintptr
	AddMediaPropertiesChanged       uintptr
	RemoveMediaPropertiesChanged    uintptr
}

func (v *iGlobalSystemMediaTransportControlsSession) VTable() *iGlobalSystemMediaTransportControlsSessionVtbl {
	return (*iGlobalSystemMediaTransportControlsSessionVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iGlobalSystemMediaTransportControlsSession) TryGetMediaPropertiesAsync() (*foundation.IAsyncOperation, error) {
	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().TryGetMediaPropertiesAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
