// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureMediaPropertiesChangedEventArgs string = "rc(Windows.Media.Control.MediaPropertiesChangedEventArgs;{7d3741cb-adf0-5cef-91ba-cfabcdd77678})"

type MediaPropertiesChangedEventArgs struct {
	ole.IUnknown
}

const GUIDiMediaPropertiesChangedEventArgs string = "7d3741cb-adf0-5cef-91ba-cfabcdd77678"
const SignatureiMediaPropertiesChangedEventArgs string = "{7d3741cb-adf0-5cef-91ba-cfabcdd77678}"

type iMediaPropertiesChangedEventArgs struct {
	ole.IInspectable
}

type iMediaPropertiesChangedEventArgsVtbl struct {
	ole.IInspectableVtbl
}

func (v *iMediaPropertiesChangedEventArgs) VTable() *iMediaPropertiesChangedEventArgsVtbl {
	return (*iMediaPropertiesChangedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}
