// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignaturePlaybackInfoChangedEventArgs string = "rc(Windows.Media.Control.PlaybackInfoChangedEventArgs;{786756c2-bc0d-50a5-8807-054291fef139})"

type PlaybackInfoChangedEventArgs struct {
	ole.IUnknown
}

const GUIDiPlaybackInfoChangedEventArgs string = "786756c2-bc0d-50a5-8807-054291fef139"
const SignatureiPlaybackInfoChangedEventArgs string = "{786756c2-bc0d-50a5-8807-054291fef139}"

type iPlaybackInfoChangedEventArgs struct {
	ole.IInspectable
}

type iPlaybackInfoChangedEventArgsVtbl struct {
	ole.IInspectableVtbl
}

func (v *iPlaybackInfoChangedEventArgs) VTable() *iPlaybackInfoChangedEventArgsVtbl {
	return (*iPlaybackInfoChangedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}
