// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package control

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureTimelinePropertiesChangedEventArgs string = "rc(Windows.Media.Control.TimelinePropertiesChangedEventArgs;{29033a2f-c923-5a77-bcaf-055ff415ad32})"

type TimelinePropertiesChangedEventArgs struct {
	ole.IUnknown
}

const GUIDiTimelinePropertiesChangedEventArgs string = "29033a2f-c923-5a77-bcaf-055ff415ad32"
const SignatureiTimelinePropertiesChangedEventArgs string = "{29033a2f-c923-5a77-bcaf-055ff415ad32}"

type iTimelinePropertiesChangedEventArgs struct {
	ole.IInspectable
}

type iTimelinePropertiesChangedEventArgsVtbl struct {
	ole.IInspectableVtbl
}

func (v *iTimelinePropertiesChangedEventArgs) VTable() *iTimelinePropertiesChangedEventArgsVtbl {
	return (*iTimelinePropertiesChangedEventArgsVtbl)(unsafe.Pointer(v.RawVTable))
}
