// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package networking

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureEndpointPair string = "rc(Windows.Networking.EndpointPair;{33a0aa36-f8fa-4b30-b856-76517c3bd06d})"

type EndpointPair struct {
	ole.IUnknown
}

func (impl *EndpointPair) GetLocalHostName() (*HostName, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.GetLocalHostName()
}

func (impl *EndpointPair) SetLocalHostName(value *HostName) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.SetLocalHostName(value)
}

func (impl *EndpointPair) GetLocalServiceName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.GetLocalServiceName()
}

func (impl *EndpointPair) SetLocalServiceName(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.SetLocalServiceName(value)
}

func (impl *EndpointPair) GetRemoteHostName() (*HostName, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.GetRemoteHostName()
}

func (impl *EndpointPair) SetRemoteHostName(value *HostName) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.SetRemoteHostName(value)
}

func (impl *EndpointPair) GetRemoteServiceName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.GetRemoteServiceName()
}

func (impl *EndpointPair) SetRemoteServiceName(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiEndpointPair))
	defer itf.Release()
	v := (*iEndpointPair)(unsafe.Pointer(itf))
	return v.SetRemoteServiceName(value)
}

const GUIDiEndpointPair string = "33a0aa36-f8fa-4b30-b856-76517c3bd06d"
const SignatureiEndpointPair string = "{33a0aa36-f8fa-4b30-b856-76517c3bd06d}"

type iEndpointPair struct {
	ole.IInspectable
}

type iEndpointPairVtbl struct {
	ole.IInspectableVtbl

	GetLocalHostName     uintptr
	SetLocalHostName     uintptr
	GetLocalServiceName  uintptr
	SetLocalServiceName  uintptr
	GetRemoteHostName    uintptr
	SetRemoteHostName    uintptr
	GetRemoteServiceName uintptr
	SetRemoteServiceName uintptr
}

func (v *iEndpointPair) VTable() *iEndpointPairVtbl {
	return (*iEndpointPairVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iEndpointPair) GetLocalHostName() (*HostName, error) {
	var out *HostName
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLocalHostName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out HostName
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iEndpointPair) SetLocalHostName(value *HostName) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetLocalHostName,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in HostName
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iEndpointPair) GetLocalServiceName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLocalServiceName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iEndpointPair) SetLocalServiceName(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetLocalServiceName,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iEndpointPair) GetRemoteHostName() (*HostName, error) {
	var out *HostName
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRemoteHostName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out HostName
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iEndpointPair) SetRemoteHostName(value *HostName) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetRemoteHostName,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in HostName
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iEndpointPair) GetRemoteServiceName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRemoteServiceName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iEndpointPair) SetRemoteServiceName(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetRemoteServiceName,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiEndpointPairFactory string = "b609d971-64e0-442b-aa6f-cc8c8f181f78"
const SignatureiEndpointPairFactory string = "{b609d971-64e0-442b-aa6f-cc8c8f181f78}"

type iEndpointPairFactory struct {
	ole.IInspectable
}

type iEndpointPairFactoryVtbl struct {
	ole.IInspectableVtbl

	EndpointPairCreateEndpointPair uintptr
}

func (v *iEndpointPairFactory) VTable() *iEndpointPairFactoryVtbl {
	return (*iEndpointPairFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func EndpointPairCreateEndpointPair(localHostName *HostName, localServiceName string, remoteHostName *HostName, remoteServiceName string) (*EndpointPair, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Networking.EndpointPair", ole.NewGUID(GUIDiEndpointPairFactory))
	if err != nil {
		return nil, err
	}
	v := (*iEndpointPairFactory)(unsafe.Pointer(inspectable))

	var out *EndpointPair
	localServiceNameHStr, err := ole.NewHString(localServiceName)
	if err != nil {
		return nil, err
	}
	remoteServiceNameHStr, err := ole.NewHString(remoteServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().EndpointPairCreateEndpointPair,
		uintptr(unsafe.Pointer(v)),              // this
		uintptr(unsafe.Pointer(localHostName)),  // in HostName
		uintptr(localServiceNameHStr),           // in string
		uintptr(unsafe.Pointer(remoteHostName)), // in HostName
		uintptr(remoteServiceNameHStr),          // in string
		uintptr(unsafe.Pointer(&out)),           // out EndpointPair
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
