// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package networking

type HostNameSortOptions uint32

const SignatureHostNameSortOptions string = "enum(Windows.Networking.HostNameSortOptions;u4)"

const (
	HostNameSortOptionsNone                       HostNameSortOptions = 0
	HostNameSortOptionsOptimizeForLongConnections HostNameSortOptions = 2
)
