// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package networking

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/networking/connectivity"
)

const SignatureHostName string = "rc(Windows.Networking.HostName;{bf8ecaad-ed96-49a7-9084-d416cae88dcb})"

type HostName struct {
	ole.IUnknown
}

func (impl *HostName) GetIPInformation() (*connectivity.IPInformation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiHostName))
	defer itf.Release()
	v := (*iHostName)(unsafe.Pointer(itf))
	return v.GetIPInformation()
}

func (impl *HostName) GetRawName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiHostName))
	defer itf.Release()
	v := (*iHostName)(unsafe.Pointer(itf))
	return v.GetRawName()
}

func (impl *HostName) GetDisplayName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiHostName))
	defer itf.Release()
	v := (*iHostName)(unsafe.Pointer(itf))
	return v.GetDisplayName()
}

func (impl *HostName) GetCanonicalName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiHostName))
	defer itf.Release()
	v := (*iHostName)(unsafe.Pointer(itf))
	return v.GetCanonicalName()
}

func (impl *HostName) GetType() (HostNameType, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiHostName))
	defer itf.Release()
	v := (*iHostName)(unsafe.Pointer(itf))
	return v.GetType()
}

func (impl *HostName) IsEqual(hostName *HostName) (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiHostName))
	defer itf.Release()
	v := (*iHostName)(unsafe.Pointer(itf))
	return v.IsEqual(hostName)
}

func (impl *HostName) ToString() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIStringable))
	defer itf.Release()
	v := (*foundation.IStringable)(unsafe.Pointer(itf))
	return v.ToString()
}

const GUIDiHostName string = "bf8ecaad-ed96-49a7-9084-d416cae88dcb"
const SignatureiHostName string = "{bf8ecaad-ed96-49a7-9084-d416cae88dcb}"

type iHostName struct {
	ole.IInspectable
}

type iHostNameVtbl struct {
	ole.IInspectableVtbl

	GetIPInformation uintptr
	GetRawName       uintptr
	GetDisplayName   uintptr
	GetCanonicalName uintptr
	GetType          uintptr
	IsEqual          uintptr
}

func (v *iHostName) VTable() *iHostNameVtbl {
	return (*iHostNameVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iHostName) GetIPInformation() (*connectivity.IPInformation, error) {
	var out *connectivity.IPInformation
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIPInformation,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out connectivity.IPInformation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iHostName) GetRawName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRawName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iHostName) GetDisplayName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDisplayName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iHostName) GetCanonicalName() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCanonicalName,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iHostName) GetType() (HostNameType, error) {
	var out HostNameType
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetType,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out HostNameType
	)

	if hr != 0 {
		return HostNameTypeDomainName, ole.NewError(hr)
	}

	return out, nil
}

func (v *iHostName) IsEqual(hostName *HostName) (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().IsEqual,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(hostName)), // in HostName
		uintptr(unsafe.Pointer(&out)),     // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiHostNameStatics string = "f68cd4bf-a388-4e8b-91ea-54dd6dd901c0"
const SignatureiHostNameStatics string = "{f68cd4bf-a388-4e8b-91ea-54dd6dd901c0}"

type iHostNameStatics struct {
	ole.IInspectable
}

type iHostNameStaticsVtbl struct {
	ole.IInspectableVtbl

	HostNameCompare uintptr
}

func (v *iHostNameStatics) VTable() *iHostNameStaticsVtbl {
	return (*iHostNameStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func HostNameCompare(value1 string, value2 string) (int32, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Networking.HostName", ole.NewGUID(GUIDiHostNameStatics))
	if err != nil {
		return 0, err
	}
	v := (*iHostNameStatics)(unsafe.Pointer(inspectable))

	var out int32
	value1HStr, err := ole.NewHString(value1)
	if err != nil {
		return 0, err
	}
	value2HStr, err := ole.NewHString(value2)
	if err != nil {
		return 0, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().HostNameCompare,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(value1HStr),           // in string
		uintptr(value2HStr),           // in string
		uintptr(unsafe.Pointer(&out)), // out int32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiHostNameFactory string = "458c23ed-712f-4576-adf1-c20b2c643558"
const SignatureiHostNameFactory string = "{458c23ed-712f-4576-adf1-c20b2c643558}"

type iHostNameFactory struct {
	ole.IInspectable
}

type iHostNameFactoryVtbl struct {
	ole.IInspectableVtbl

	HostNameCreateHostName uintptr
}

func (v *iHostNameFactory) VTable() *iHostNameFactoryVtbl {
	return (*iHostNameFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func HostNameCreateHostName(hostName string) (*HostName, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Networking.HostName", ole.NewGUID(GUIDiHostNameFactory))
	if err != nil {
		return nil, err
	}
	v := (*iHostNameFactory)(unsafe.Pointer(inspectable))

	var out *HostName
	hostNameHStr, err := ole.NewHString(hostName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().HostNameCreateHostName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(hostNameHStr),         // in string
		uintptr(unsafe.Pointer(&out)), // out HostName
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
