// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package networking

type HostNameType int32

const SignatureHostNameType string = "enum(Windows.Networking.HostNameType;i4)"

const (
	HostNameTypeDomainName HostNameType = 0
	HostNameTypeIpv4       HostNameType = 1
	HostNameTypeIpv6       HostNameType = 2
	HostNameTypeBluetooth  HostNameType = 3
)
