// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

const SignatureRoundTripTimeStatistics string = "struct(Windows.Networking.Sockets.RoundTripTimeStatistics;u4;u4;u4;u4)"

type RoundTripTimeStatistics struct {
	Variance uint32

	Max uint32

	Min uint32

	Sum uint32
}
