// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

type SocketActivityConnectedStandbyAction int32

const SignatureSocketActivityConnectedStandbyAction string = "enum(Windows.Networking.Sockets.SocketActivityConnectedStandbyAction;i4)"

const (
	SocketActivityConnectedStandbyActionDoNotWake SocketActivityConnectedStandbyAction = 0
	SocketActivityConnectedStandbyActionWake      SocketActivityConnectedStandbyAction = 1
)
