// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

type SocketProtectionLevel int32

const SignatureSocketProtectionLevel string = "enum(Windows.Networking.Sockets.SocketProtectionLevel;i4)"

const (
	SocketProtectionLevelPlainSocket                                SocketProtectionLevel = 0
	SocketProtectionLevelSsl                                        SocketProtectionLevel = 1
	SocketProtectionLevelSslAllowNullEncryption                     SocketProtectionLevel = 2
	SocketProtectionLevelBluetoothEncryptionAllowNullAuthentication SocketProtectionLevel = 3
	SocketProtectionLevelBluetoothEncryptionWithAuthentication      SocketProtectionLevel = 4
	SocketProtectionLevelSsl3AllowWeakEncryption                    SocketProtectionLevel = 5
	SocketProtectionLevelTls10                                      SocketProtectionLevel = 6
	SocketProtectionLevelTls11                                      SocketProtectionLevel = 7
	SocketProtectionLevelTls12                                      SocketProtectionLevel = 8
	SocketProtectionLevelUnspecified                                SocketProtectionLevel = 9
)
