// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

type SocketSslErrorSeverity int32

const SignatureSocketSslErrorSeverity string = "enum(Windows.Networking.Sockets.SocketSslErrorSeverity;i4)"

const (
	SocketSslErrorSeverityNone      SocketSslErrorSeverity = 0
	SocketSslErrorSeverityIgnorable SocketSslErrorSeverity = 1
	SocketSslErrorSeverityFatal     SocketSslErrorSeverity = 2
)
