// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/storage/streams"
)

const SignatureSocketActivityContext string = "rc(Windows.Networking.Sockets.SocketActivityContext;{43b04d64-4c85-4396-a637-1d973f6ebd49})"

type SocketActivityContext struct {
	ole.IUnknown
}

func (impl *SocketActivityContext) GetData() (*streams.IBuffer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiSocketActivityContext))
	defer itf.Release()
	v := (*iSocketActivityContext)(unsafe.Pointer(itf))
	return v.GetData()
}

const GUIDiSocketActivityContext string = "43b04d64-4c85-4396-a637-1d973f6ebd49"
const SignatureiSocketActivityContext string = "{43b04d64-4c85-4396-a637-1d973f6ebd49}"

type iSocketActivityContext struct {
	ole.IInspectable
}

type iSocketActivityContextVtbl struct {
	ole.IInspectableVtbl

	GetData uintptr
}

func (v *iSocketActivityContext) VTable() *iSocketActivityContextVtbl {
	return (*iSocketActivityContextVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iSocketActivityContext) GetData() (*streams.IBuffer, error) {
	var out *streams.IBuffer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetData,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out streams.IBuffer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiSocketActivityContextFactory string = "b99fc3c3-088c-4388-83ae-2525138e049a"
const SignatureiSocketActivityContextFactory string = "{b99fc3c3-088c-4388-83ae-2525138e049a}"

type iSocketActivityContextFactory struct {
	ole.IInspectable
}

type iSocketActivityContextFactoryVtbl struct {
	ole.IInspectableVtbl

	SocketActivityContextCreate uintptr
}

func (v *iSocketActivityContextFactory) VTable() *iSocketActivityContextFactoryVtbl {
	return (*iSocketActivityContextFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func SocketActivityContextCreate(data *streams.IBuffer) (*SocketActivityContext, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Networking.Sockets.SocketActivityContext", ole.NewGUID(GUIDiSocketActivityContextFactory))
	if err != nil {
		return nil, err
	}
	v := (*iSocketActivityContextFactory)(unsafe.Pointer(inspectable))

	var out *SocketActivityContext
	hr, _, _ := syscall.SyscallN(
		v.VTable().SocketActivityContextCreate,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(data)), // in streams.IBuffer
		uintptr(unsafe.Pointer(&out)), // out SocketActivityContext
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
