// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureStreamSocketListenerInformation string = "rc(Windows.Networking.Sockets.StreamSocketListenerInformation;{e62ba82f-a63a-430b-bf62-29e93e5633b4})"

type StreamSocketListenerInformation struct {
	ole.IUnknown
}

func (impl *StreamSocketListenerInformation) GetLocalPort() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerInformation))
	defer itf.Release()
	v := (*iStreamSocketListenerInformation)(unsafe.Pointer(itf))
	return v.GetLocalPort()
}

const GUIDiStreamSocketListenerInformation string = "e62ba82f-a63a-430b-bf62-29e93e5633b4"
const SignatureiStreamSocketListenerInformation string = "{e62ba82f-a63a-430b-bf62-29e93e5633b4}"

type iStreamSocketListenerInformation struct {
	ole.IInspectable
}

type iStreamSocketListenerInformationVtbl struct {
	ole.IInspectableVtbl

	GetLocalPort uintptr
}

func (v *iStreamSocketListenerInformation) VTable() *iStreamSocketListenerInformationVtbl {
	return (*iStreamSocketListenerInformationVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketListenerInformation) GetLocalPort() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLocalPort,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
