// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/networking"
	"github.com/saltosystems/winrt-go/windows/networking/connectivity"
	"github.com/saltosystems/winrt-go/windows/storage/streams"
)

const SignatureStreamSocket string = "rc(Windows.Networking.Sockets.StreamSocket;{69a22cf3-fc7b-4857-af38-f6e7de6a5b49})"

type StreamSocket struct {
	ole.IUnknown
}

func NewStreamSocket() (*StreamSocket, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Networking.Sockets.StreamSocket")
	if err != nil {
		return nil, err
	}
	return (*StreamSocket)(unsafe.Pointer(inspectable)), nil
}

func (impl *StreamSocket) GetControl() (*StreamSocketControl, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.GetControl()
}

func (impl *StreamSocket) GetInformation() (*StreamSocketInformation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.GetInformation()
}

func (impl *StreamSocket) GetInputStream() (*streams.IInputStream, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.GetInputStream()
}

func (impl *StreamSocket) GetOutputStream() (*streams.IOutputStream, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.GetOutputStream()
}

func (impl *StreamSocket) ConnectWithEndpointPairAsync(endpointPair *networking.EndpointPair) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.ConnectWithEndpointPairAsync(endpointPair)
}

func (impl *StreamSocket) ConnectAsync(remoteHostName *networking.HostName, remoteServiceName string) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.ConnectAsync(remoteHostName, remoteServiceName)
}

func (impl *StreamSocket) ConnectWithEndpointPairAndProtectionLevelAsync(endpointPair *networking.EndpointPair, protectionLevel SocketProtectionLevel) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.ConnectWithEndpointPairAndProtectionLevelAsync(endpointPair, protectionLevel)
}

func (impl *StreamSocket) ConnectWithProtectionLevelAsync(remoteHostName *networking.HostName, remoteServiceName string, protectionLevel SocketProtectionLevel) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.ConnectWithProtectionLevelAsync(remoteHostName, remoteServiceName, protectionLevel)
}

func (impl *StreamSocket) UpgradeToSslAsync(protectionLevel SocketProtectionLevel, validationHostName *networking.HostName) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket))
	defer itf.Release()
	v := (*iStreamSocket)(unsafe.Pointer(itf))
	return v.UpgradeToSslAsync(protectionLevel, validationHostName)
}

func (impl *StreamSocket) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

func (impl *StreamSocket) ConnectWithProtectionLevelAndAdapterAsync(remoteHostName *networking.HostName, remoteServiceName string, protectionLevel SocketProtectionLevel, adapter *connectivity.NetworkAdapter) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket2))
	defer itf.Release()
	v := (*iStreamSocket2)(unsafe.Pointer(itf))
	return v.ConnectWithProtectionLevelAndAdapterAsync(remoteHostName, remoteServiceName, protectionLevel, adapter)
}

func (impl *StreamSocket) CancelIOAsync() (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket3))
	defer itf.Release()
	v := (*iStreamSocket3)(unsafe.Pointer(itf))
	return v.CancelIOAsync()
}

func (impl *StreamSocket) EnableTransferOwnership(taskId syscall.GUID) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket3))
	defer itf.Release()
	v := (*iStreamSocket3)(unsafe.Pointer(itf))
	return v.EnableTransferOwnership(taskId)
}

func (impl *StreamSocket) EnableTransferOwnershipWithConnectedStandbyAction(taskId syscall.GUID, connectedStandbyAction SocketActivityConnectedStandbyAction) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket3))
	defer itf.Release()
	v := (*iStreamSocket3)(unsafe.Pointer(itf))
	return v.EnableTransferOwnershipWithConnectedStandbyAction(taskId, connectedStandbyAction)
}

func (impl *StreamSocket) TransferOwnership(socketId string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket3))
	defer itf.Release()
	v := (*iStreamSocket3)(unsafe.Pointer(itf))
	return v.TransferOwnership(socketId)
}

func (impl *StreamSocket) TransferOwnershipWithContext(socketId string, data *SocketActivityContext) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket3))
	defer itf.Release()
	v := (*iStreamSocket3)(unsafe.Pointer(itf))
	return v.TransferOwnershipWithContext(socketId, data)
}

func (impl *StreamSocket) TransferOwnershipWithContextAndKeepAliveTime(socketId string, data *SocketActivityContext, keepAliveTime foundation.TimeSpan) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocket3))
	defer itf.Release()
	v := (*iStreamSocket3)(unsafe.Pointer(itf))
	return v.TransferOwnershipWithContextAndKeepAliveTime(socketId, data, keepAliveTime)
}

const GUIDiStreamSocket string = "69a22cf3-fc7b-4857-af38-f6e7de6a5b49"
const SignatureiStreamSocket string = "{69a22cf3-fc7b-4857-af38-f6e7de6a5b49}"

type iStreamSocket struct {
	ole.IInspectable
}

type iStreamSocketVtbl struct {
	ole.IInspectableVtbl

	GetControl                                     uintptr
	GetInformation                                 uintptr
	GetInputStream                                 uintptr
	GetOutputStream                                uintptr
	ConnectWithEndpointPairAsync                   uintptr
	ConnectAsync                                   uintptr
	ConnectWithEndpointPairAndProtectionLevelAsync uintptr
	ConnectWithProtectionLevelAsync                uintptr
	UpgradeToSslAsync                              uintptr
}

func (v *iStreamSocket) VTable() *iStreamSocketVtbl {
	return (*iStreamSocketVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocket) GetControl() (*StreamSocketControl, error) {
	var out *StreamSocketControl
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetControl,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StreamSocketControl
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) GetInformation() (*StreamSocketInformation, error) {
	var out *StreamSocketInformation
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInformation,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StreamSocketInformation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) GetInputStream() (*streams.IInputStream, error) {
	var out *streams.IInputStream
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInputStream,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out streams.IInputStream
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) GetOutputStream() (*streams.IOutputStream, error) {
	var out *streams.IOutputStream
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetOutputStream,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out streams.IOutputStream
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) ConnectWithEndpointPairAsync(endpointPair *networking.EndpointPair) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	hr, _, _ := syscall.SyscallN(
		v.VTable().ConnectWithEndpointPairAsync,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(endpointPair)), // in networking.EndpointPair
		uintptr(unsafe.Pointer(&out)),         // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) ConnectAsync(remoteHostName *networking.HostName, remoteServiceName string) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	remoteServiceNameHStr, err := ole.NewHString(remoteServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().ConnectAsync,
		uintptr(unsafe.Pointer(v)),              // this
		uintptr(unsafe.Pointer(remoteHostName)), // in networking.HostName
		uintptr(remoteServiceNameHStr),          // in string
		uintptr(unsafe.Pointer(&out)),           // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) ConnectWithEndpointPairAndProtectionLevelAsync(endpointPair *networking.EndpointPair, protectionLevel SocketProtectionLevel) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	hr, _, _ := syscall.SyscallN(
		v.VTable().ConnectWithEndpointPairAndProtectionLevelAsync,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(endpointPair)), // in networking.EndpointPair
		uintptr(protectionLevel),              // in SocketProtectionLevel
		uintptr(unsafe.Pointer(&out)),         // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) ConnectWithProtectionLevelAsync(remoteHostName *networking.HostName, remoteServiceName string, protectionLevel SocketProtectionLevel) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	remoteServiceNameHStr, err := ole.NewHString(remoteServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().ConnectWithProtectionLevelAsync,
		uintptr(unsafe.Pointer(v)),              // this
		uintptr(unsafe.Pointer(remoteHostName)), // in networking.HostName
		uintptr(remoteServiceNameHStr),          // in string
		uintptr(protectionLevel),                // in SocketProtectionLevel
		uintptr(unsafe.Pointer(&out)),           // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket) UpgradeToSslAsync(protectionLevel SocketProtectionLevel, validationHostName *networking.HostName) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	hr, _, _ := syscall.SyscallN(
		v.VTable().UpgradeToSslAsync,
		uintptr(unsafe.Pointer(v)),                  // this
		uintptr(protectionLevel),                    // in SocketProtectionLevel
		uintptr(unsafe.Pointer(validationHostName)), // in networking.HostName
		uintptr(unsafe.Pointer(&out)),               // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiStreamSocket2 string = "29d0e575-f314-4d09-adf0-0fbd967fbd9f"
const SignatureiStreamSocket2 string = "{29d0e575-f314-4d09-adf0-0fbd967fbd9f}"

type iStreamSocket2 struct {
	ole.IInspectable
}

type iStreamSocket2Vtbl struct {
	ole.IInspectableVtbl

	ConnectWithProtectionLevelAndAdapterAsync uintptr
}

func (v *iStreamSocket2) VTable() *iStreamSocket2Vtbl {
	return (*iStreamSocket2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocket2) ConnectWithProtectionLevelAndAdapterAsync(remoteHostName *networking.HostName, remoteServiceName string, protectionLevel SocketProtectionLevel, adapter *connectivity.NetworkAdapter) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	remoteServiceNameHStr, err := ole.NewHString(remoteServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().ConnectWithProtectionLevelAndAdapterAsync,
		uintptr(unsafe.Pointer(v)),              // this
		uintptr(unsafe.Pointer(remoteHostName)), // in networking.HostName
		uintptr(remoteServiceNameHStr),          // in string
		uintptr(protectionLevel),                // in SocketProtectionLevel
		uintptr(unsafe.Pointer(adapter)),        // in connectivity.NetworkAdapter
		uintptr(unsafe.Pointer(&out)),           // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiStreamSocket3 string = "3f430b00-9d28-4854-bac3-2301941ec223"
const SignatureiStreamSocket3 string = "{3f430b00-9d28-4854-bac3-2301941ec223}"

type iStreamSocket3 struct {
	ole.IInspectable
}

type iStreamSocket3Vtbl struct {
	ole.IInspectableVtbl

	CancelIOAsync                                     uintptr
	EnableTransferOwnership                           uintptr
	EnableTransferOwnershipWithConnectedStandbyAction uintptr
	TransferOwnership                                 uintptr
	TransferOwnershipWithContext                      uintptr
	TransferOwnershipWithContextAndKeepAliveTime      uintptr
}

func (v *iStreamSocket3) VTable() *iStreamSocket3Vtbl {
	return (*iStreamSocket3Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocket3) CancelIOAsync() (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	hr, _, _ := syscall.SyscallN(
		v.VTable().CancelIOAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocket3) EnableTransferOwnership(taskId syscall.GUID) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().EnableTransferOwnership,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(&taskId)), // in syscall.GUID
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocket3) EnableTransferOwnershipWithConnectedStandbyAction(taskId syscall.GUID, connectedStandbyAction SocketActivityConnectedStandbyAction) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().EnableTransferOwnershipWithConnectedStandbyAction,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(&taskId)), // in syscall.GUID
		uintptr(connectedStandbyAction),  // in SocketActivityConnectedStandbyAction
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocket3) TransferOwnership(socketId string) error {
	socketIdHStr, err := ole.NewHString(socketId)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().TransferOwnership,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(socketIdHStr),      // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocket3) TransferOwnershipWithContext(socketId string, data *SocketActivityContext) error {
	socketIdHStr, err := ole.NewHString(socketId)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().TransferOwnershipWithContext,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(socketIdHStr),         // in string
		uintptr(unsafe.Pointer(data)), // in SocketActivityContext
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocket3) TransferOwnershipWithContextAndKeepAliveTime(socketId string, data *SocketActivityContext, keepAliveTime foundation.TimeSpan) error {
	socketIdHStr, err := ole.NewHString(socketId)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().TransferOwnershipWithContextAndKeepAliveTime,
		uintptr(unsafe.Pointer(v)),              // this
		uintptr(socketIdHStr),                   // in string
		uintptr(unsafe.Pointer(data)),           // in SocketActivityContext
		uintptr(unsafe.Pointer(&keepAliveTime)), // in foundation.TimeSpan
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStreamSocketStatics string = "a420bc4a-6e2e-4af5-b556-355ae0cd4f29"
const SignatureiStreamSocketStatics string = "{a420bc4a-6e2e-4af5-b556-355ae0cd4f29}"

type iStreamSocketStatics struct {
	ole.IInspectable
}

type iStreamSocketStaticsVtbl struct {
	ole.IInspectableVtbl

	StreamSocketGetEndpointPairsAsync                uintptr
	StreamSocketGetEndpointPairsWithSortOptionsAsync uintptr
}

func (v *iStreamSocketStatics) VTable() *iStreamSocketStaticsVtbl {
	return (*iStreamSocketStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func StreamSocketGetEndpointPairsAsync(remoteHostName *networking.HostName, remoteServiceName string) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Networking.Sockets.StreamSocket", ole.NewGUID(GUIDiStreamSocketStatics))
	if err != nil {
		return nil, err
	}
	v := (*iStreamSocketStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	remoteServiceNameHStr, err := ole.NewHString(remoteServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().StreamSocketGetEndpointPairsAsync,
		uintptr(unsafe.Pointer(v)),              // this
		uintptr(unsafe.Pointer(remoteHostName)), // in networking.HostName
		uintptr(remoteServiceNameHStr),          // in string
		uintptr(unsafe.Pointer(&out)),           // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func StreamSocketGetEndpointPairsWithSortOptionsAsync(remoteHostName *networking.HostName, remoteServiceName string, sortOptions networking.HostNameSortOptions) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Networking.Sockets.StreamSocket", ole.NewGUID(GUIDiStreamSocketStatics))
	if err != nil {
		return nil, err
	}
	v := (*iStreamSocketStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	remoteServiceNameHStr, err := ole.NewHString(remoteServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().StreamSocketGetEndpointPairsWithSortOptionsAsync,
		uintptr(unsafe.Pointer(v)),              // this
		uintptr(unsafe.Pointer(remoteHostName)), // in networking.HostName
		uintptr(remoteServiceNameHStr),          // in string
		uintptr(sortOptions),                    // in networking.HostNameSortOptions
		uintptr(unsafe.Pointer(&out)),           // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
