// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
	"github.com/saltosystems/winrt-go/windows/security/cryptography/certificates"
)

const SignatureStreamSocketControl string = "rc(Windows.Networking.Sockets.StreamSocketControl;{fe25adf1-92ab-4af3-9992-0f4c85e36cc4})"

type StreamSocketControl struct {
	ole.IUnknown
}

func (impl *StreamSocketControl) GetNoDelay() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.GetNoDelay()
}

func (impl *StreamSocketControl) SetNoDelay(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.SetNoDelay(value)
}

func (impl *StreamSocketControl) GetKeepAlive() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.GetKeepAlive()
}

func (impl *StreamSocketControl) SetKeepAlive(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.SetKeepAlive(value)
}

func (impl *StreamSocketControl) GetOutboundBufferSizeInBytes() (uint32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.GetOutboundBufferSizeInBytes()
}

func (impl *StreamSocketControl) SetOutboundBufferSizeInBytes(value uint32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.SetOutboundBufferSizeInBytes(value)
}

func (impl *StreamSocketControl) GetQualityOfService() (SocketQualityOfService, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.GetQualityOfService()
}

func (impl *StreamSocketControl) SetQualityOfService(value SocketQualityOfService) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.SetQualityOfService(value)
}

func (impl *StreamSocketControl) GetOutboundUnicastHopLimit() (uint8, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.GetOutboundUnicastHopLimit()
}

func (impl *StreamSocketControl) SetOutboundUnicastHopLimit(value uint8) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl))
	defer itf.Release()
	v := (*iStreamSocketControl)(unsafe.Pointer(itf))
	return v.SetOutboundUnicastHopLimit(value)
}

func (impl *StreamSocketControl) GetIgnorableServerCertificateErrors() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl2))
	defer itf.Release()
	v := (*iStreamSocketControl2)(unsafe.Pointer(itf))
	return v.GetIgnorableServerCertificateErrors()
}

func (impl *StreamSocketControl) GetSerializeConnectionAttempts() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl3))
	defer itf.Release()
	v := (*iStreamSocketControl3)(unsafe.Pointer(itf))
	return v.GetSerializeConnectionAttempts()
}

func (impl *StreamSocketControl) SetSerializeConnectionAttempts(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl3))
	defer itf.Release()
	v := (*iStreamSocketControl3)(unsafe.Pointer(itf))
	return v.SetSerializeConnectionAttempts(value)
}

func (impl *StreamSocketControl) GetClientCertificate() (*certificates.Certificate, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl3))
	defer itf.Release()
	v := (*iStreamSocketControl3)(unsafe.Pointer(itf))
	return v.GetClientCertificate()
}

func (impl *StreamSocketControl) SetClientCertificate(value *certificates.Certificate) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl3))
	defer itf.Release()
	v := (*iStreamSocketControl3)(unsafe.Pointer(itf))
	return v.SetClientCertificate(value)
}

func (impl *StreamSocketControl) GetMinProtectionLevel() (SocketProtectionLevel, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl4))
	defer itf.Release()
	v := (*iStreamSocketControl4)(unsafe.Pointer(itf))
	return v.GetMinProtectionLevel()
}

func (impl *StreamSocketControl) SetMinProtectionLevel(value SocketProtectionLevel) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketControl4))
	defer itf.Release()
	v := (*iStreamSocketControl4)(unsafe.Pointer(itf))
	return v.SetMinProtectionLevel(value)
}

const GUIDiStreamSocketControl string = "fe25adf1-92ab-4af3-9992-0f4c85e36cc4"
const SignatureiStreamSocketControl string = "{fe25adf1-92ab-4af3-9992-0f4c85e36cc4}"

type iStreamSocketControl struct {
	ole.IInspectable
}

type iStreamSocketControlVtbl struct {
	ole.IInspectableVtbl

	GetNoDelay                   uintptr
	SetNoDelay                   uintptr
	GetKeepAlive                 uintptr
	SetKeepAlive                 uintptr
	GetOutboundBufferSizeInBytes uintptr
	SetOutboundBufferSizeInBytes uintptr
	GetQualityOfService          uintptr
	SetQualityOfService          uintptr
	GetOutboundUnicastHopLimit   uintptr
	SetOutboundUnicastHopLimit   uintptr
}

func (v *iStreamSocketControl) VTable() *iStreamSocketControlVtbl {
	return (*iStreamSocketControlVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketControl) GetNoDelay() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNoDelay,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl) SetNoDelay(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetNoDelay,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketControl) GetKeepAlive() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeepAlive,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl) SetKeepAlive(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetKeepAlive,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketControl) GetOutboundBufferSizeInBytes() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetOutboundBufferSizeInBytes,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl) SetOutboundBufferSizeInBytes(value uint32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetOutboundBufferSizeInBytes,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in uint32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketControl) GetQualityOfService() (SocketQualityOfService, error) {
	var out SocketQualityOfService
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetQualityOfService,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out SocketQualityOfService
	)

	if hr != 0 {
		return SocketQualityOfServiceNormal, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl) SetQualityOfService(value SocketQualityOfService) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetQualityOfService,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in SocketQualityOfService
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketControl) GetOutboundUnicastHopLimit() (uint8, error) {
	var out uint8
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetOutboundUnicastHopLimit,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint8
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl) SetOutboundUnicastHopLimit(value uint8) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetOutboundUnicastHopLimit,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in uint8
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStreamSocketControl2 string = "c2d09a56-060f-44c1-b8e2-1fbf60bd62c5"
const SignatureiStreamSocketControl2 string = "{c2d09a56-060f-44c1-b8e2-1fbf60bd62c5}"

type iStreamSocketControl2 struct {
	ole.IInspectable
}

type iStreamSocketControl2Vtbl struct {
	ole.IInspectableVtbl

	GetIgnorableServerCertificateErrors uintptr
}

func (v *iStreamSocketControl2) VTable() *iStreamSocketControl2Vtbl {
	return (*iStreamSocketControl2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketControl2) GetIgnorableServerCertificateErrors() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIgnorableServerCertificateErrors,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiStreamSocketControl3 string = "c56a444c-4e74-403e-894c-b31cae5c7342"
const SignatureiStreamSocketControl3 string = "{c56a444c-4e74-403e-894c-b31cae5c7342}"

type iStreamSocketControl3 struct {
	ole.IInspectable
}

type iStreamSocketControl3Vtbl struct {
	ole.IInspectableVtbl

	GetSerializeConnectionAttempts uintptr
	SetSerializeConnectionAttempts uintptr
	GetClientCertificate           uintptr
	SetClientCertificate           uintptr
}

func (v *iStreamSocketControl3) VTable() *iStreamSocketControl3Vtbl {
	return (*iStreamSocketControl3Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketControl3) GetSerializeConnectionAttempts() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSerializeConnectionAttempts,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl3) SetSerializeConnectionAttempts(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetSerializeConnectionAttempts,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketControl3) GetClientCertificate() (*certificates.Certificate, error) {
	var out *certificates.Certificate
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetClientCertificate,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out certificates.Certificate
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl3) SetClientCertificate(value *certificates.Certificate) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetClientCertificate,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in certificates.Certificate
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStreamSocketControl4 string = "964e2b3d-ec27-4888-b3ce-c74b418423ad"
const SignatureiStreamSocketControl4 string = "{964e2b3d-ec27-4888-b3ce-c74b418423ad}"

type iStreamSocketControl4 struct {
	ole.IInspectable
}

type iStreamSocketControl4Vtbl struct {
	ole.IInspectableVtbl

	GetMinProtectionLevel uintptr
	SetMinProtectionLevel uintptr
}

func (v *iStreamSocketControl4) VTable() *iStreamSocketControl4Vtbl {
	return (*iStreamSocketControl4Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketControl4) GetMinProtectionLevel() (SocketProtectionLevel, error) {
	var out SocketProtectionLevel
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMinProtectionLevel,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out SocketProtectionLevel
	)

	if hr != 0 {
		return SocketProtectionLevelPlainSocket, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketControl4) SetMinProtectionLevel(value SocketProtectionLevel) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetMinProtectionLevel,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in SocketProtectionLevel
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
