// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureStreamSocketListenerControl string = "rc(Windows.Networking.Sockets.StreamSocketListenerControl;{20d8c576-8d8a-4dba-9722-a16c4d984980})"

type StreamSocketListenerControl struct {
	ole.IUnknown
}

func (impl *StreamSocketListenerControl) GetQualityOfService() (SocketQualityOfService, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl))
	defer itf.Release()
	v := (*iStreamSocketListenerControl)(unsafe.Pointer(itf))
	return v.GetQualityOfService()
}

func (impl *StreamSocketListenerControl) SetQualityOfService(value SocketQualityOfService) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl))
	defer itf.Release()
	v := (*iStreamSocketListenerControl)(unsafe.Pointer(itf))
	return v.SetQualityOfService(value)
}

func (impl *StreamSocketListenerControl) GetNoDelay() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.GetNoDelay()
}

func (impl *StreamSocketListenerControl) SetNoDelay(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.SetNoDelay(value)
}

func (impl *StreamSocketListenerControl) GetKeepAlive() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.GetKeepAlive()
}

func (impl *StreamSocketListenerControl) SetKeepAlive(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.SetKeepAlive(value)
}

func (impl *StreamSocketListenerControl) GetOutboundBufferSizeInBytes() (uint32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.GetOutboundBufferSizeInBytes()
}

func (impl *StreamSocketListenerControl) SetOutboundBufferSizeInBytes(value uint32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.SetOutboundBufferSizeInBytes(value)
}

func (impl *StreamSocketListenerControl) GetOutboundUnicastHopLimit() (uint8, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.GetOutboundUnicastHopLimit()
}

func (impl *StreamSocketListenerControl) SetOutboundUnicastHopLimit(value uint8) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListenerControl2))
	defer itf.Release()
	v := (*iStreamSocketListenerControl2)(unsafe.Pointer(itf))
	return v.SetOutboundUnicastHopLimit(value)
}

const GUIDiStreamSocketListenerControl string = "20d8c576-8d8a-4dba-9722-a16c4d984980"
const SignatureiStreamSocketListenerControl string = "{20d8c576-8d8a-4dba-9722-a16c4d984980}"

type iStreamSocketListenerControl struct {
	ole.IInspectable
}

type iStreamSocketListenerControlVtbl struct {
	ole.IInspectableVtbl

	GetQualityOfService uintptr
	SetQualityOfService uintptr
}

func (v *iStreamSocketListenerControl) VTable() *iStreamSocketListenerControlVtbl {
	return (*iStreamSocketListenerControlVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketListenerControl) GetQualityOfService() (SocketQualityOfService, error) {
	var out SocketQualityOfService
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetQualityOfService,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out SocketQualityOfService
	)

	if hr != 0 {
		return SocketQualityOfServiceNormal, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListenerControl) SetQualityOfService(value SocketQualityOfService) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetQualityOfService,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in SocketQualityOfService
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStreamSocketListenerControl2 string = "948bb665-2c3e-404b-b8b0-8eb249a2b0a1"
const SignatureiStreamSocketListenerControl2 string = "{948bb665-2c3e-404b-b8b0-8eb249a2b0a1}"

type iStreamSocketListenerControl2 struct {
	ole.IInspectable
}

type iStreamSocketListenerControl2Vtbl struct {
	ole.IInspectableVtbl

	GetNoDelay                   uintptr
	SetNoDelay                   uintptr
	GetKeepAlive                 uintptr
	SetKeepAlive                 uintptr
	GetOutboundBufferSizeInBytes uintptr
	SetOutboundBufferSizeInBytes uintptr
	GetOutboundUnicastHopLimit   uintptr
	SetOutboundUnicastHopLimit   uintptr
}

func (v *iStreamSocketListenerControl2) VTable() *iStreamSocketListenerControl2Vtbl {
	return (*iStreamSocketListenerControl2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketListenerControl2) GetNoDelay() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNoDelay,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListenerControl2) SetNoDelay(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetNoDelay,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketListenerControl2) GetKeepAlive() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKeepAlive,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListenerControl2) SetKeepAlive(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetKeepAlive,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketListenerControl2) GetOutboundBufferSizeInBytes() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetOutboundBufferSizeInBytes,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListenerControl2) SetOutboundBufferSizeInBytes(value uint32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetOutboundBufferSizeInBytes,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in uint32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketListenerControl2) GetOutboundUnicastHopLimit() (uint8, error) {
	var out uint8
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetOutboundUnicastHopLimit,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint8
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListenerControl2) SetOutboundUnicastHopLimit(value uint8) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetOutboundUnicastHopLimit,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in uint8
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
