// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package sockets

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/networking"
	"github.com/saltosystems/winrt-go/windows/networking/connectivity"
)

const SignatureStreamSocketListener string = "rc(Windows.Networking.Sockets.StreamSocketListener;{ff513437-df9f-4df0-bf82-0ec5d7b35aae})"

type StreamSocketListener struct {
	ole.IUnknown
}

func NewStreamSocketListener() (*StreamSocketListener, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Networking.Sockets.StreamSocketListener")
	if err != nil {
		return nil, err
	}
	return (*StreamSocketListener)(unsafe.Pointer(inspectable)), nil
}

func (impl *StreamSocketListener) GetControl() (*StreamSocketListenerControl, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener))
	defer itf.Release()
	v := (*iStreamSocketListener)(unsafe.Pointer(itf))
	return v.GetControl()
}

func (impl *StreamSocketListener) GetInformation() (*StreamSocketListenerInformation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener))
	defer itf.Release()
	v := (*iStreamSocketListener)(unsafe.Pointer(itf))
	return v.GetInformation()
}

func (impl *StreamSocketListener) BindServiceNameAsync(localServiceName string) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener))
	defer itf.Release()
	v := (*iStreamSocketListener)(unsafe.Pointer(itf))
	return v.BindServiceNameAsync(localServiceName)
}

func (impl *StreamSocketListener) BindEndpointAsync(localHostName *networking.HostName, localServiceName string) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener))
	defer itf.Release()
	v := (*iStreamSocketListener)(unsafe.Pointer(itf))
	return v.BindEndpointAsync(localHostName, localServiceName)
}

func (impl *StreamSocketListener) AddConnectionReceived(eventHandler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener))
	defer itf.Release()
	v := (*iStreamSocketListener)(unsafe.Pointer(itf))
	return v.AddConnectionReceived(eventHandler)
}

func (impl *StreamSocketListener) RemoveConnectionReceived(eventCookie foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener))
	defer itf.Release()
	v := (*iStreamSocketListener)(unsafe.Pointer(itf))
	return v.RemoveConnectionReceived(eventCookie)
}

func (impl *StreamSocketListener) Close() error {
	itf := impl.MustQueryInterface(ole.NewGUID(foundation.GUIDIClosable))
	defer itf.Release()
	v := (*foundation.IClosable)(unsafe.Pointer(itf))
	return v.Close()
}

func (impl *StreamSocketListener) BindServiceNameWithProtectionLevelAsync(localServiceName string, protectionLevel SocketProtectionLevel) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener2))
	defer itf.Release()
	v := (*iStreamSocketListener2)(unsafe.Pointer(itf))
	return v.BindServiceNameWithProtectionLevelAsync(localServiceName, protectionLevel)
}

func (impl *StreamSocketListener) BindServiceNameWithProtectionLevelAndAdapterAsync(localServiceName string, protectionLevel SocketProtectionLevel, adapter *connectivity.NetworkAdapter) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener2))
	defer itf.Release()
	v := (*iStreamSocketListener2)(unsafe.Pointer(itf))
	return v.BindServiceNameWithProtectionLevelAndAdapterAsync(localServiceName, protectionLevel, adapter)
}

func (impl *StreamSocketListener) CancelIOAsync() (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener3))
	defer itf.Release()
	v := (*iStreamSocketListener3)(unsafe.Pointer(itf))
	return v.CancelIOAsync()
}

func (impl *StreamSocketListener) EnableTransferOwnership(taskId syscall.GUID) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener3))
	defer itf.Release()
	v := (*iStreamSocketListener3)(unsafe.Pointer(itf))
	return v.EnableTransferOwnership(taskId)
}

func (impl *StreamSocketListener) EnableTransferOwnershipWithConnectedStandbyAction(taskId syscall.GUID, connectedStandbyAction SocketActivityConnectedStandbyAction) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener3))
	defer itf.Release()
	v := (*iStreamSocketListener3)(unsafe.Pointer(itf))
	return v.EnableTransferOwnershipWithConnectedStandbyAction(taskId, connectedStandbyAction)
}

func (impl *StreamSocketListener) TransferOwnership(socketId string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener3))
	defer itf.Release()
	v := (*iStreamSocketListener3)(unsafe.Pointer(itf))
	return v.TransferOwnership(socketId)
}

func (impl *StreamSocketListener) TransferOwnershipWithContext(socketId string, data *SocketActivityContext) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStreamSocketListener3))
	defer itf.Release()
	v := (*iStreamSocketListener3)(unsafe.Pointer(itf))
	return v.TransferOwnershipWithContext(socketId, data)
}

const GUIDiStreamSocketListener string = "ff513437-df9f-4df0-bf82-0ec5d7b35aae"
const SignatureiStreamSocketListener string = "{ff513437-df9f-4df0-bf82-0ec5d7b35aae}"

type iStreamSocketListener struct {
	ole.IInspectable
}

type iStreamSocketListenerVtbl struct {
	ole.IInspectableVtbl

	GetControl               uintptr
	GetInformation           uintptr
	BindServiceNameAsync     uintptr
	BindEndpointAsync        uintptr
	AddConnectionReceived    uintptr
	RemoveConnectionReceived uintptr
}

func (v *iStreamSocketListener) VTable() *iStreamSocketListenerVtbl {
	return (*iStreamSocketListenerVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketListener) GetControl() (*StreamSocketListenerControl, error) {
	var out *StreamSocketListenerControl
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetControl,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StreamSocketListenerControl
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListener) GetInformation() (*StreamSocketListenerInformation, error) {
	var out *StreamSocketListenerInformation
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetInformation,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StreamSocketListenerInformation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListener) BindServiceNameAsync(localServiceName string) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	localServiceNameHStr, err := ole.NewHString(localServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().BindServiceNameAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(localServiceNameHStr), // in string
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListener) BindEndpointAsync(localHostName *networking.HostName, localServiceName string) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	localServiceNameHStr, err := ole.NewHString(localServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().BindEndpointAsync,
		uintptr(unsafe.Pointer(v)),             // this
		uintptr(unsafe.Pointer(localHostName)), // in networking.HostName
		uintptr(localServiceNameHStr),          // in string
		uintptr(unsafe.Pointer(&out)),          // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListener) AddConnectionReceived(eventHandler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddConnectionReceived,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(eventHandler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),         // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListener) RemoveConnectionReceived(eventCookie foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveConnectionReceived,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(&eventCookie)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiStreamSocketListener2 string = "658dc13e-bb3e-4458-b232-ed1088694b98"
const SignatureiStreamSocketListener2 string = "{658dc13e-bb3e-4458-b232-ed1088694b98}"

type iStreamSocketListener2 struct {
	ole.IInspectable
}

type iStreamSocketListener2Vtbl struct {
	ole.IInspectableVtbl

	BindServiceNameWithProtectionLevelAsync           uintptr
	BindServiceNameWithProtectionLevelAndAdapterAsync uintptr
}

func (v *iStreamSocketListener2) VTable() *iStreamSocketListener2Vtbl {
	return (*iStreamSocketListener2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketListener2) BindServiceNameWithProtectionLevelAsync(localServiceName string, protectionLevel SocketProtectionLevel) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	localServiceNameHStr, err := ole.NewHString(localServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().BindServiceNameWithProtectionLevelAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(localServiceNameHStr), // in string
		uintptr(protectionLevel),      // in SocketProtectionLevel
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListener2) BindServiceNameWithProtectionLevelAndAdapterAsync(localServiceName string, protectionLevel SocketProtectionLevel, adapter *connectivity.NetworkAdapter) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	localServiceNameHStr, err := ole.NewHString(localServiceName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().BindServiceNameWithProtectionLevelAndAdapterAsync,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(localServiceNameHStr),    // in string
		uintptr(protectionLevel),         // in SocketProtectionLevel
		uintptr(unsafe.Pointer(adapter)), // in connectivity.NetworkAdapter
		uintptr(unsafe.Pointer(&out)),    // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiStreamSocketListener3 string = "4798201c-bdf8-4919-8542-28d450e74507"
const SignatureiStreamSocketListener3 string = "{4798201c-bdf8-4919-8542-28d450e74507}"

type iStreamSocketListener3 struct {
	ole.IInspectable
}

type iStreamSocketListener3Vtbl struct {
	ole.IInspectableVtbl

	CancelIOAsync                                     uintptr
	EnableTransferOwnership                           uintptr
	EnableTransferOwnershipWithConnectedStandbyAction uintptr
	TransferOwnership                                 uintptr
	TransferOwnershipWithContext                      uintptr
}

func (v *iStreamSocketListener3) VTable() *iStreamSocketListener3Vtbl {
	return (*iStreamSocketListener3Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStreamSocketListener3) CancelIOAsync() (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	hr, _, _ := syscall.SyscallN(
		v.VTable().CancelIOAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStreamSocketListener3) EnableTransferOwnership(taskId syscall.GUID) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().EnableTransferOwnership,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(&taskId)), // in syscall.GUID
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketListener3) EnableTransferOwnershipWithConnectedStandbyAction(taskId syscall.GUID, connectedStandbyAction SocketActivityConnectedStandbyAction) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().EnableTransferOwnershipWithConnectedStandbyAction,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(&taskId)), // in syscall.GUID
		uintptr(connectedStandbyAction),  // in SocketActivityConnectedStandbyAction
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketListener3) TransferOwnership(socketId string) error {
	socketIdHStr, err := ole.NewHString(socketId)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().TransferOwnership,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(socketIdHStr),      // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStreamSocketListener3) TransferOwnershipWithContext(socketId string, data *SocketActivityContext) error {
	socketIdHStr, err := ole.NewHString(socketId)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().TransferOwnershipWithContext,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(socketIdHStr),         // in string
		uintptr(unsafe.Pointer(data)), // in SocketActivityContext
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
